# These are supported funding model platforms

custom: ['https://paypal.me/JonathanMelly/5CHF','https://paypal.me/JonathanMelly/10CHF','https://paypal.me/JonathanMelly/EUR','https://paypal.me/JonathanMelly/CHF']# Replace with up to 4 custom sponsorship URLs e.g., ['link1', 'link2']
