//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/interpreter/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace interpreter.antlr {
#pragma warning disable 3021
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class CosmosParser : Parser {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		LABEL_AUTEUR=10, LABEL_DATE=11, CONTENU_DATE=12, ENTREPRISE_ENTETE=13, 
		DESCRIPTION_ENTETE=14, DEBUT=15, BIBLIOTHEQUE=16, FIN=17, DE_LA_TRANSMISSION=18, 
		ZONE=19, ALORS=20, OPERATEUR_COMPARAISON_EGAL=21, OPERATEUR_DIFFERENT=22, 
		VRAI=23, FAUX=24, ET=25, OU=26, OU_EXCLUSIF=27, EST=28, OPERATEUR_EGAL=29, 
		VARIABLE=30, PARENTHESE_GAUCHE=31, PARENTHESE_DROITE=32, LE_TEXTE=33, 
		VALEUR_TEXTE=34, LE_NOMBRE=35, VALEUR_NOMBRE=36, OPERATEUR_PLUS=37, OPERATEUR_MOINS=38, 
		OPERATEUR_FOIS=39, OPERATEUR_DIVISE=40, MOT=41, VIRGULE=42, POINT=43, 
		POINT_INTERROGATION=44, SUIVANT=45, DEUX_POINT=46, TAB=47, RETCHAR=48, 
		ESPACE=49, COMMENTAIRE_LIGNE=50, COMMENTAIRE=51, NOOP=52;
	public const int
		RULE_programme = 0, RULE_entete = 1, RULE_auteur = 2, RULE_date = 3, RULE_entreprise = 4, 
		RULE_description = 5, RULE_mainStart = 6, RULE_mainEnd = 7, RULE_instruction = 8, 
		RULE_instruction_simple = 9, RULE_instruction_complexe = 10, RULE_afficher = 11, 
		RULE_allouer = 12, RULE_affecter = 13, RULE_zone_memoire = 14, RULE_selection = 15, 
		RULE_sinon_si = 16, RULE_sinon = 17, RULE_condition = 18, RULE_postcondition = 19, 
		RULE_operateur_comparaison = 20, RULE_operateur_booleen = 21, RULE_expression = 22, 
		RULE_expression_calculable = 23, RULE_expression_representant_numeraire = 24, 
		RULE_expression_variable = 25, RULE_expression_textuelle = 26, RULE_expression_numeraire = 27, 
		RULE_operateur_mathematique = 28;
	public static readonly string[] ruleNames = {
		"programme", "entete", "auteur", "date", "entreprise", "description", 
		"mainStart", "mainEnd", "instruction", "instruction_simple", "instruction_complexe", 
		"afficher", "allouer", "affecter", "zone_memoire", "selection", "sinon_si", 
		"sinon", "condition", "postcondition", "operateur_comparaison", "operateur_booleen", 
		"expression", "expression_calculable", "expression_representant_numeraire", 
		"expression_variable", "expression_textuelle", "expression_numeraire", 
		"operateur_mathematique"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Afficher'", "'Allouer'", "'avec'", "'Copier'", "'dans'", "'Si'", 
		"'sinon si'", "'et sinon'", "'la valeur de'", "'Auteur:'", "'Date:'", 
		null, "'Entreprise:'", "'Description:'", "'Voici les ordres du programme'", 
		"'à classer dans la bibliothèque'", "'Fin'", "'de la transmission'", "'la zone mémoire'", 
		"'alors'", null, null, "'vrai'", "'faux'", "'et'", "'ou'", "'ou au contraire'", 
		"'est'", "'='", null, "'('", "')'", "'le texte'", null, "'le nombre'", 
		null, null, null, null, null, null, "','", "'.'", "'?'", "'>>'", "':'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, "LABEL_AUTEUR", 
		"LABEL_DATE", "CONTENU_DATE", "ENTREPRISE_ENTETE", "DESCRIPTION_ENTETE", 
		"DEBUT", "BIBLIOTHEQUE", "FIN", "DE_LA_TRANSMISSION", "ZONE", "ALORS", 
		"OPERATEUR_COMPARAISON_EGAL", "OPERATEUR_DIFFERENT", "VRAI", "FAUX", "ET", 
		"OU", "OU_EXCLUSIF", "EST", "OPERATEUR_EGAL", "VARIABLE", "PARENTHESE_GAUCHE", 
		"PARENTHESE_DROITE", "LE_TEXTE", "VALEUR_TEXTE", "LE_NOMBRE", "VALEUR_NOMBRE", 
		"OPERATEUR_PLUS", "OPERATEUR_MOINS", "OPERATEUR_FOIS", "OPERATEUR_DIVISE", 
		"MOT", "VIRGULE", "POINT", "POINT_INTERROGATION", "SUIVANT", "DEUX_POINT", 
		"TAB", "RETCHAR", "ESPACE", "COMMENTAIRE_LIGNE", "COMMENTAIRE", "NOOP"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete("Use IRecognizer.Vocabulary instead.")]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Cosmos.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public CosmosParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgrammeContext : ParserRuleContext {
		public EnteteContext entete() {
			return GetRuleContext<EnteteContext>(0);
		}
		public MainStartContext mainStart() {
			return GetRuleContext<MainStartContext>(0);
		}
		public MainEndContext mainEnd() {
			return GetRuleContext<MainEndContext>(0);
		}
		public ITerminalNode Eof() { return GetToken(CosmosParser.Eof, 0); }
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		public ProgrammeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_programme; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterProgramme(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitProgramme(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgramme(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgrammeContext programme() {
		ProgrammeContext _localctx = new ProgrammeContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_programme);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 58; entete();
			State = 60;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 59; Match(RETCHAR);
				}
				}
				State = 62;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==RETCHAR );
			State = 64; mainStart();
			State = 66;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 65; Match(RETCHAR);
				}
				}
				State = 68;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==RETCHAR );
			State = 71;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 70; instruction();
				}
				}
				State = 73;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 76;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,3,_ctx) ) {
			case 1:
				{
				State = 75; Match(RETCHAR);
				}
				break;
			}
			State = 79;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,4,_ctx) ) {
			case 1:
				{
				State = 78; Match(RETCHAR);
				}
				break;
			}
			State = 82;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==RETCHAR) {
				{
				State = 81; Match(RETCHAR);
				}
			}

			State = 84; mainEnd();
			State = 88;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
			while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1+1 ) {
					{
					{
					State = 85;
					MatchWildcard();
					}
					} 
				}
				State = 90;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,6,_ctx);
			}
			State = 91; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnteteContext : ParserRuleContext {
		public AuteurContext auteur() {
			return GetRuleContext<AuteurContext>(0);
		}
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public DateContext date() {
			return GetRuleContext<DateContext>(0);
		}
		public EntrepriseContext entreprise() {
			return GetRuleContext<EntrepriseContext>(0);
		}
		public DescriptionContext description() {
			return GetRuleContext<DescriptionContext>(0);
		}
		public EnteteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entete; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterEntete(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitEntete(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntete(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnteteContext entete() {
		EnteteContext _localctx = new EnteteContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_entete);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; auteur();
			State = 94; Match(RETCHAR);
			State = 95; date();
			State = 96; Match(RETCHAR);
			State = 97; entreprise();
			State = 98; Match(RETCHAR);
			State = 99; description();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AuteurContext : ParserRuleContext {
		public ITerminalNode LABEL_AUTEUR() { return GetToken(CosmosParser.LABEL_AUTEUR, 0); }
		public ITerminalNode[] MOT() { return GetTokens(CosmosParser.MOT); }
		public ITerminalNode MOT(int i) {
			return GetToken(CosmosParser.MOT, i);
		}
		public AuteurContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_auteur; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterAuteur(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitAuteur(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAuteur(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AuteurContext auteur() {
		AuteurContext _localctx = new AuteurContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_auteur);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 101; Match(LABEL_AUTEUR);
			State = 102; Match(MOT);
			State = 104;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==MOT) {
				{
				State = 103; Match(MOT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DateContext : ParserRuleContext {
		public ITerminalNode LABEL_DATE() { return GetToken(CosmosParser.LABEL_DATE, 0); }
		public ITerminalNode CONTENU_DATE() { return GetToken(CosmosParser.CONTENU_DATE, 0); }
		public DateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterDate(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitDate(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DateContext date() {
		DateContext _localctx = new DateContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_date);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106; Match(LABEL_DATE);
			State = 107; Match(CONTENU_DATE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntrepriseContext : ParserRuleContext {
		public ITerminalNode ENTREPRISE_ENTETE() { return GetToken(CosmosParser.ENTREPRISE_ENTETE, 0); }
		public ITerminalNode MOT() { return GetToken(CosmosParser.MOT, 0); }
		public EntrepriseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entreprise; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterEntreprise(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitEntreprise(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntreprise(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EntrepriseContext entreprise() {
		EntrepriseContext _localctx = new EntrepriseContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_entreprise);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 109; Match(ENTREPRISE_ENTETE);
			State = 110; Match(MOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DescriptionContext : ParserRuleContext {
		public ITerminalNode DESCRIPTION_ENTETE() { return GetToken(CosmosParser.DESCRIPTION_ENTETE, 0); }
		public ITerminalNode[] MOT() { return GetTokens(CosmosParser.MOT); }
		public ITerminalNode MOT(int i) {
			return GetToken(CosmosParser.MOT, i);
		}
		public ITerminalNode[] VIRGULE() { return GetTokens(CosmosParser.VIRGULE); }
		public ITerminalNode VIRGULE(int i) {
			return GetToken(CosmosParser.VIRGULE, i);
		}
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public DescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_description; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitDescription(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDescription(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DescriptionContext description() {
		DescriptionContext _localctx = new DescriptionContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_description);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 112; Match(DESCRIPTION_ENTETE);
			State = 114;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 113; Match(MOT);
				}
				}
				State = 116;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==MOT );
			State = 127;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==VIRGULE) {
				{
				{
				State = 118; Match(VIRGULE);
				State = 119; Match(RETCHAR);
				State = 121;
				_errHandler.Sync(this);
				_la = _input.La(1);
				do {
					{
					{
					State = 120; Match(MOT);
					}
					}
					State = 123;
					_errHandler.Sync(this);
					_la = _input.La(1);
				} while ( _la==MOT );
				}
				}
				State = 129;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MainStartContext : ParserRuleContext {
		public IToken nomDuProgramme;
		public IToken bibliotheque;
		public ITerminalNode DEBUT() { return GetToken(CosmosParser.DEBUT, 0); }
		public ITerminalNode DEUX_POINT() { return GetToken(CosmosParser.DEUX_POINT, 0); }
		public ITerminalNode[] MOT() { return GetTokens(CosmosParser.MOT); }
		public ITerminalNode MOT(int i) {
			return GetToken(CosmosParser.MOT, i);
		}
		public ITerminalNode BIBLIOTHEQUE() { return GetToken(CosmosParser.BIBLIOTHEQUE, 0); }
		public MainStartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mainStart; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterMainStart(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitMainStart(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMainStart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MainStartContext mainStart() {
		MainStartContext _localctx = new MainStartContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_mainStart);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130; Match(DEBUT);
			State = 131; _localctx.nomDuProgramme = Match(MOT);
			State = 134;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==BIBLIOTHEQUE) {
				{
				State = 132; Match(BIBLIOTHEQUE);
				State = 133; _localctx.bibliotheque = Match(MOT);
				}
			}

			State = 136; Match(DEUX_POINT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MainEndContext : ParserRuleContext {
		public ITerminalNode FIN() { return GetToken(CosmosParser.FIN, 0); }
		public ITerminalNode POINT() { return GetToken(CosmosParser.POINT, 0); }
		public ITerminalNode DE_LA_TRANSMISSION() { return GetToken(CosmosParser.DE_LA_TRANSMISSION, 0); }
		public MainEndContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_mainEnd; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterMainEnd(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitMainEnd(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMainEnd(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MainEndContext mainEnd() {
		MainEndContext _localctx = new MainEndContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_mainEnd);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 138; Match(FIN);
			State = 140;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==DE_LA_TRANSMISSION) {
				{
				State = 139; Match(DE_LA_TRANSMISSION);
				}
			}

			State = 142; Match(POINT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InstructionContext : ParserRuleContext {
		public Instruction_simpleContext instruction_simple() {
			return GetRuleContext<Instruction_simpleContext>(0);
		}
		public Instruction_complexeContext instruction_complexe() {
			return GetRuleContext<Instruction_complexeContext>(0);
		}
		public InstructionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InstructionContext instruction() {
		InstructionContext _localctx = new InstructionContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_instruction);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 146;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,13,_ctx) ) {
			case 1:
				{
				State = 144; instruction_simple();
				}
				break;

			case 2:
				{
				State = 145; instruction_complexe();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_simpleContext : ParserRuleContext {
		public ITerminalNode POINT() { return GetToken(CosmosParser.POINT, 0); }
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public AfficherContext afficher() {
			return GetRuleContext<AfficherContext>(0);
		}
		public AllouerContext allouer() {
			return GetRuleContext<AllouerContext>(0);
		}
		public AffecterContext affecter() {
			return GetRuleContext<AffecterContext>(0);
		}
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public Instruction_simpleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_simple; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_simple(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_simple(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_simple(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_simpleContext instruction_simple() {
		Instruction_simpleContext _localctx = new Instruction_simpleContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_instruction_simple);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 149;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 148; Match(TAB);
				}
				}
				State = 151;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 156;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case T__0:
				{
				State = 153; afficher();
				}
				break;
			case T__1:
				{
				State = 154; allouer();
				}
				break;
			case T__3:
			case T__8:
			case VARIABLE:
				{
				State = 155; affecter();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 158; Match(POINT);
			State = 159; Match(RETCHAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_complexeContext : ParserRuleContext {
		public SelectionContext selection() {
			return GetRuleContext<SelectionContext>(0);
		}
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public Instruction_complexeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_complexe; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_complexe(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_complexe(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_complexe(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_complexeContext instruction_complexe() {
		Instruction_complexeContext _localctx = new Instruction_complexeContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_instruction_complexe);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 162;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 161; Match(TAB);
				}
				}
				State = 164;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			{
			State = 166; selection();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AfficherContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AfficherContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_afficher; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterAfficher(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitAfficher(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAfficher(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AfficherContext afficher() {
		AfficherContext _localctx = new AfficherContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_afficher);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 168; Match(T__0);
			State = 169; expression();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AllouerContext : ParserRuleContext {
		public Zone_memoireContext zone_memoire() {
			return GetRuleContext<Zone_memoireContext>(0);
		}
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public AllouerContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_allouer; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterAllouer(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitAllouer(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAllouer(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AllouerContext allouer() {
		AllouerContext _localctx = new AllouerContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_allouer);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 171; Match(T__1);
			State = 172; zone_memoire();
			State = 175;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==T__2) {
				{
				State = 173; Match(T__2);
				State = 174; expression();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AffecterContext : ParserRuleContext {
		public ExpressionContext expression() {
			return GetRuleContext<ExpressionContext>(0);
		}
		public Zone_memoireContext zone_memoire() {
			return GetRuleContext<Zone_memoireContext>(0);
		}
		public Expression_variableContext expression_variable() {
			return GetRuleContext<Expression_variableContext>(0);
		}
		public ITerminalNode OPERATEUR_EGAL() { return GetToken(CosmosParser.OPERATEUR_EGAL, 0); }
		public AffecterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_affecter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterAffecter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitAffecter(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAffecter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AffecterContext affecter() {
		AffecterContext _localctx = new AffecterContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_affecter);
		try {
			State = 186;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case T__3:
				EnterOuterAlt(_localctx, 1);
				{
				{
				State = 177; Match(T__3);
				State = 178; expression();
				State = 179; Match(T__4);
				State = 180; zone_memoire();
				}
				}
				break;
			case T__8:
			case VARIABLE:
				EnterOuterAlt(_localctx, 2);
				{
				{
				State = 182; expression_variable();
				State = 183; Match(OPERATEUR_EGAL);
				State = 184; expression();
				}
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Zone_memoireContext : ParserRuleContext {
		public ITerminalNode VARIABLE() { return GetToken(CosmosParser.VARIABLE, 0); }
		public ITerminalNode ZONE() { return GetToken(CosmosParser.ZONE, 0); }
		public Zone_memoireContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_zone_memoire; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterZone_memoire(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitZone_memoire(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitZone_memoire(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Zone_memoireContext zone_memoire() {
		Zone_memoireContext _localctx = new Zone_memoireContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_zone_memoire);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 189;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==ZONE) {
				{
				State = 188; Match(ZONE);
				}
			}

			State = 191; Match(VARIABLE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectionContext : ParserRuleContext {
		public ConditionContext si;
		public ITerminalNode ALORS() { return GetToken(CosmosParser.ALORS, 0); }
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public ITerminalNode POINT_INTERROGATION() { return GetToken(CosmosParser.POINT_INTERROGATION, 0); }
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		public Sinon_siContext[] sinon_si() {
			return GetRuleContexts<Sinon_siContext>();
		}
		public Sinon_siContext sinon_si(int i) {
			return GetRuleContext<Sinon_siContext>(i);
		}
		public SinonContext sinon() {
			return GetRuleContext<SinonContext>(0);
		}
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public SelectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selection; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterSelection(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitSelection(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectionContext selection() {
		SelectionContext _localctx = new SelectionContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_selection);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 193; Match(T__5);
			State = 194; _localctx.si = condition();
			State = 195; Match(ALORS);
			State = 196; Match(RETCHAR);
			State = 198;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 197; instruction();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 200;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,20,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			State = 205;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,21,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 202; sinon_si();
					}
					} 
				}
				State = 207;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,21,_ctx);
			}
			State = 209;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,22,_ctx) ) {
			case 1:
				{
				State = 208; sinon();
				}
				break;
			}
			State = 212;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 211; Match(TAB);
				}
				}
				State = 214;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 216; Match(POINT_INTERROGATION);
			State = 217; Match(RETCHAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Sinon_siContext : ParserRuleContext {
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public ITerminalNode ALORS() { return GetToken(CosmosParser.ALORS, 0); }
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		public Sinon_siContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sinon_si; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterSinon_si(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitSinon_si(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSinon_si(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Sinon_siContext sinon_si() {
		Sinon_siContext _localctx = new Sinon_siContext(_ctx, State);
		EnterRule(_localctx, 32, RULE_sinon_si);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 220;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 219; Match(TAB);
				}
				}
				State = 222;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 224; Match(T__6);
			State = 225; condition();
			State = 226; Match(ALORS);
			State = 227; Match(RETCHAR);
			State = 229;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 228; instruction();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 231;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,25,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SinonContext : ParserRuleContext {
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public InstructionContext[] instruction() {
			return GetRuleContexts<InstructionContext>();
		}
		public InstructionContext instruction(int i) {
			return GetRuleContext<InstructionContext>(i);
		}
		public SinonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_sinon; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterSinon(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitSinon(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSinon(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SinonContext sinon() {
		SinonContext _localctx = new SinonContext(_ctx, State);
		EnterRule(_localctx, 34, RULE_sinon);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 234;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 233; Match(TAB);
				}
				}
				State = 236;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 238; Match(T__7);
			State = 239; Match(RETCHAR);
			State = 241;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 240; instruction();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 243;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,27,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		public ExpressionContext left;
		public ExpressionContext right;
		public PostconditionContext[] postcondition() {
			return GetRuleContexts<PostconditionContext>();
		}
		public PostconditionContext postcondition(int i) {
			return GetRuleContext<PostconditionContext>(i);
		}
		public Operateur_comparaisonContext operateur_comparaison() {
			return GetRuleContext<Operateur_comparaisonContext>(0);
		}
		public ITerminalNode VARIABLE() { return GetToken(CosmosParser.VARIABLE, 0); }
		public ITerminalNode EST() { return GetToken(CosmosParser.EST, 0); }
		public ITerminalNode VRAI() { return GetToken(CosmosParser.VRAI, 0); }
		public ITerminalNode FAUX() { return GetToken(CosmosParser.FAUX, 0); }
		public ExpressionContext[] expression() {
			return GetRuleContexts<ExpressionContext>();
		}
		public ExpressionContext expression(int i) {
			return GetRuleContext<ExpressionContext>(i);
		}
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterCondition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitCondition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(_ctx, State);
		EnterRule(_localctx, 36, RULE_condition);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 255;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,29,_ctx) ) {
			case 1:
				{
				{
				State = 245; _localctx.left = expression();
				State = 246; operateur_comparaison();
				State = 247; _localctx.right = expression();
				}
				}
				break;

			case 2:
				{
				State = 253;
				_errHandler.Sync(this);
				switch (_input.La(1)) {
				case VARIABLE:
					{
					State = 249; Match(VARIABLE);
					State = 250; Match(EST);
					State = 251; Match(VRAI);
					}
					break;
				case FAUX:
					{
					State = 252; Match(FAUX);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				break;
			}
			State = 260;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,30,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 257; postcondition();
					}
					} 
				}
				State = 262;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,30,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PostconditionContext : ParserRuleContext {
		public Operateur_booleenContext operateur_booleen() {
			return GetRuleContext<Operateur_booleenContext>(0);
		}
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public PostconditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_postcondition; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterPostcondition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitPostcondition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPostcondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PostconditionContext postcondition() {
		PostconditionContext _localctx = new PostconditionContext(_ctx, State);
		EnterRule(_localctx, 38, RULE_postcondition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 263; operateur_booleen();
			State = 264; condition();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Operateur_comparaisonContext : ParserRuleContext {
		public ITerminalNode OPERATEUR_COMPARAISON_EGAL() { return GetToken(CosmosParser.OPERATEUR_COMPARAISON_EGAL, 0); }
		public ITerminalNode OPERATEUR_DIFFERENT() { return GetToken(CosmosParser.OPERATEUR_DIFFERENT, 0); }
		public Operateur_comparaisonContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operateur_comparaison; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterOperateur_comparaison(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitOperateur_comparaison(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperateur_comparaison(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Operateur_comparaisonContext operateur_comparaison() {
		Operateur_comparaisonContext _localctx = new Operateur_comparaisonContext(_ctx, State);
		EnterRule(_localctx, 40, RULE_operateur_comparaison);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 266;
			_la = _input.La(1);
			if ( !(_la==OPERATEUR_COMPARAISON_EGAL || _la==OPERATEUR_DIFFERENT) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Operateur_booleenContext : ParserRuleContext {
		public ITerminalNode ET() { return GetToken(CosmosParser.ET, 0); }
		public ITerminalNode OU() { return GetToken(CosmosParser.OU, 0); }
		public ITerminalNode OU_EXCLUSIF() { return GetToken(CosmosParser.OU_EXCLUSIF, 0); }
		public Operateur_booleenContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operateur_booleen; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterOperateur_booleen(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitOperateur_booleen(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperateur_booleen(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Operateur_booleenContext operateur_booleen() {
		Operateur_booleenContext _localctx = new Operateur_booleenContext(_ctx, State);
		EnterRule(_localctx, 42, RULE_operateur_booleen);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << ET) | (1L << OU) | (1L << OU_EXCLUSIF))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExpressionContext : ParserRuleContext {
		public Expression_textuelleContext expression_textuelle() {
			return GetRuleContext<Expression_textuelleContext>(0);
		}
		public Expression_calculableContext expression_calculable() {
			return GetRuleContext<Expression_calculableContext>(0);
		}
		public ExpressionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExpressionContext expression() {
		ExpressionContext _localctx = new ExpressionContext(_ctx, State);
		EnterRule(_localctx, 44, RULE_expression);
		try {
			State = 272;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case LE_TEXTE:
			case VALEUR_TEXTE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 270; expression_textuelle();
				}
				break;
			case T__8:
			case VARIABLE:
			case PARENTHESE_GAUCHE:
			case LE_NOMBRE:
			case VALEUR_NOMBRE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 271; expression_calculable();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_calculableContext : ParserRuleContext {
		public Expression_representant_numeraireContext expression_representant_numeraire() {
			return GetRuleContext<Expression_representant_numeraireContext>(0);
		}
		public ITerminalNode PARENTHESE_GAUCHE() { return GetToken(CosmosParser.PARENTHESE_GAUCHE, 0); }
		public Expression_calculableContext[] expression_calculable() {
			return GetRuleContexts<Expression_calculableContext>();
		}
		public Expression_calculableContext expression_calculable(int i) {
			return GetRuleContext<Expression_calculableContext>(i);
		}
		public ITerminalNode PARENTHESE_DROITE() { return GetToken(CosmosParser.PARENTHESE_DROITE, 0); }
		public Operateur_mathematiqueContext[] operateur_mathematique() {
			return GetRuleContexts<Operateur_mathematiqueContext>();
		}
		public Operateur_mathematiqueContext operateur_mathematique(int i) {
			return GetRuleContext<Operateur_mathematiqueContext>(i);
		}
		public Expression_calculableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_calculable; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_calculable(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_calculable(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_calculable(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_calculableContext expression_calculable() {
		Expression_calculableContext _localctx = new Expression_calculableContext(_ctx, State);
		EnterRule(_localctx, 46, RULE_expression_calculable);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 279;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case T__8:
			case VARIABLE:
			case LE_NOMBRE:
			case VALEUR_NOMBRE:
				{
				State = 274; expression_representant_numeraire();
				}
				break;
			case PARENTHESE_GAUCHE:
				{
				State = 275; Match(PARENTHESE_GAUCHE);
				State = 276; expression_calculable();
				State = 277; Match(PARENTHESE_DROITE);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 286;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,33,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 281; operateur_mathematique();
					State = 282; expression_calculable();
					}
					} 
				}
				State = 288;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,33,_ctx);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_representant_numeraireContext : ParserRuleContext {
		public Expression_numeraireContext expression_numeraire() {
			return GetRuleContext<Expression_numeraireContext>(0);
		}
		public Expression_variableContext expression_variable() {
			return GetRuleContext<Expression_variableContext>(0);
		}
		public Expression_representant_numeraireContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_representant_numeraire; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_representant_numeraire(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_representant_numeraire(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_representant_numeraire(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_representant_numeraireContext expression_representant_numeraire() {
		Expression_representant_numeraireContext _localctx = new Expression_representant_numeraireContext(_ctx, State);
		EnterRule(_localctx, 48, RULE_expression_representant_numeraire);
		try {
			State = 291;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case LE_NOMBRE:
			case VALEUR_NOMBRE:
				EnterOuterAlt(_localctx, 1);
				{
				State = 289; expression_numeraire();
				}
				break;
			case T__8:
			case VARIABLE:
				EnterOuterAlt(_localctx, 2);
				{
				State = 290; expression_variable();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_variableContext : ParserRuleContext {
		public ITerminalNode VARIABLE() { return GetToken(CosmosParser.VARIABLE, 0); }
		public Expression_variableContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_variable; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_variable(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_variable(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_variable(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_variableContext expression_variable() {
		Expression_variableContext _localctx = new Expression_variableContext(_ctx, State);
		EnterRule(_localctx, 50, RULE_expression_variable);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 294;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==T__8) {
				{
				State = 293; Match(T__8);
				}
			}

			State = 296; Match(VARIABLE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_textuelleContext : ParserRuleContext {
		public ITerminalNode VALEUR_TEXTE() { return GetToken(CosmosParser.VALEUR_TEXTE, 0); }
		public ITerminalNode LE_TEXTE() { return GetToken(CosmosParser.LE_TEXTE, 0); }
		public Expression_textuelleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_textuelle; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_textuelle(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_textuelle(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_textuelle(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_textuelleContext expression_textuelle() {
		Expression_textuelleContext _localctx = new Expression_textuelleContext(_ctx, State);
		EnterRule(_localctx, 52, RULE_expression_textuelle);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 299;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LE_TEXTE) {
				{
				State = 298; Match(LE_TEXTE);
				}
			}

			State = 301; Match(VALEUR_TEXTE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_numeraireContext : ParserRuleContext {
		public ITerminalNode VALEUR_NOMBRE() { return GetToken(CosmosParser.VALEUR_NOMBRE, 0); }
		public ITerminalNode LE_NOMBRE() { return GetToken(CosmosParser.LE_NOMBRE, 0); }
		public Expression_numeraireContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_numeraire; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_numeraire(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_numeraire(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_numeraire(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_numeraireContext expression_numeraire() {
		Expression_numeraireContext _localctx = new Expression_numeraireContext(_ctx, State);
		EnterRule(_localctx, 54, RULE_expression_numeraire);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 304;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LE_NOMBRE) {
				{
				State = 303; Match(LE_NOMBRE);
				}
			}

			State = 306; Match(VALEUR_NOMBRE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Operateur_mathematiqueContext : ParserRuleContext {
		public ITerminalNode OPERATEUR_PLUS() { return GetToken(CosmosParser.OPERATEUR_PLUS, 0); }
		public ITerminalNode OPERATEUR_MOINS() { return GetToken(CosmosParser.OPERATEUR_MOINS, 0); }
		public ITerminalNode OPERATEUR_FOIS() { return GetToken(CosmosParser.OPERATEUR_FOIS, 0); }
		public ITerminalNode OPERATEUR_DIVISE() { return GetToken(CosmosParser.OPERATEUR_DIVISE, 0); }
		public Operateur_mathematiqueContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_operateur_mathematique; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterOperateur_mathematique(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitOperateur_mathematique(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOperateur_mathematique(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Operateur_mathematiqueContext operateur_mathematique() {
		Operateur_mathematiqueContext _localctx = new Operateur_mathematiqueContext(_ctx, State);
		EnterRule(_localctx, 56, RULE_operateur_mathematique);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 308;
			_la = _input.La(1);
			if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << OPERATEUR_PLUS) | (1L << OPERATEUR_MOINS) | (1L << OPERATEUR_FOIS) | (1L << OPERATEUR_DIVISE))) != 0)) ) {
			_errHandler.RecoverInline(this);
			} else {
				if (_input.La(1) == TokenConstants.Eof) {
					matchedEOF = true;
				}

				_errHandler.ReportMatch(this);
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\x36\x139\x4\x2"+
		"\t\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4"+
		"\t\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x4\x19\t\x19\x4\x1A\t\x1A\x4\x1B"+
		"\t\x1B\x4\x1C\t\x1C\x4\x1D\t\x1D\x4\x1E\t\x1E\x3\x2\x3\x2\x6\x2?\n\x2"+
		"\r\x2\xE\x2@\x3\x2\x3\x2\x6\x2\x45\n\x2\r\x2\xE\x2\x46\x3\x2\x6\x2J\n"+
		"\x2\r\x2\xE\x2K\x3\x2\x5\x2O\n\x2\x3\x2\x5\x2R\n\x2\x3\x2\x5\x2U\n\x2"+
		"\x3\x2\x3\x2\a\x2Y\n\x2\f\x2\xE\x2\\\v\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3"+
		"\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x4\x3\x4\x3\x4\x5\x4k\n\x4\x3\x5\x3"+
		"\x5\x3\x5\x3\x6\x3\x6\x3\x6\x3\a\x3\a\x6\au\n\a\r\a\xE\av\x3\a\x3\a\x3"+
		"\a\x6\a|\n\a\r\a\xE\a}\a\a\x80\n\a\f\a\xE\a\x83\v\a\x3\b\x3\b\x3\b\x3"+
		"\b\x5\b\x89\n\b\x3\b\x3\b\x3\t\x3\t\x5\t\x8F\n\t\x3\t\x3\t\x3\n\x3\n\x5"+
		"\n\x95\n\n\x3\v\x6\v\x98\n\v\r\v\xE\v\x99\x3\v\x3\v\x3\v\x5\v\x9F\n\v"+
		"\x3\v\x3\v\x3\v\x3\f\x6\f\xA5\n\f\r\f\xE\f\xA6\x3\f\x3\f\x3\r\x3\r\x3"+
		"\r\x3\xE\x3\xE\x3\xE\x3\xE\x5\xE\xB2\n\xE\x3\xF\x3\xF\x3\xF\x3\xF\x3\xF"+
		"\x3\xF\x3\xF\x3\xF\x3\xF\x5\xF\xBD\n\xF\x3\x10\x5\x10\xC0\n\x10\x3\x10"+
		"\x3\x10\x3\x11\x3\x11\x3\x11\x3\x11\x3\x11\x6\x11\xC9\n\x11\r\x11\xE\x11"+
		"\xCA\x3\x11\a\x11\xCE\n\x11\f\x11\xE\x11\xD1\v\x11\x3\x11\x5\x11\xD4\n"+
		"\x11\x3\x11\x6\x11\xD7\n\x11\r\x11\xE\x11\xD8\x3\x11\x3\x11\x3\x11\x3"+
		"\x12\x6\x12\xDF\n\x12\r\x12\xE\x12\xE0\x3\x12\x3\x12\x3\x12\x3\x12\x3"+
		"\x12\x6\x12\xE8\n\x12\r\x12\xE\x12\xE9\x3\x13\x6\x13\xED\n\x13\r\x13\xE"+
		"\x13\xEE\x3\x13\x3\x13\x3\x13\x6\x13\xF4\n\x13\r\x13\xE\x13\xF5\x3\x14"+
		"\x3\x14\x3\x14\x3\x14\x3\x14\x3\x14\x3\x14\x3\x14\x5\x14\x100\n\x14\x5"+
		"\x14\x102\n\x14\x3\x14\a\x14\x105\n\x14\f\x14\xE\x14\x108\v\x14\x3\x15"+
		"\x3\x15\x3\x15\x3\x16\x3\x16\x3\x17\x3\x17\x3\x18\x3\x18\x5\x18\x113\n"+
		"\x18\x3\x19\x3\x19\x3\x19\x3\x19\x3\x19\x5\x19\x11A\n\x19\x3\x19\x3\x19"+
		"\x3\x19\a\x19\x11F\n\x19\f\x19\xE\x19\x122\v\x19\x3\x1A\x3\x1A\x5\x1A"+
		"\x126\n\x1A\x3\x1B\x5\x1B\x129\n\x1B\x3\x1B\x3\x1B\x3\x1C\x5\x1C\x12E"+
		"\n\x1C\x3\x1C\x3\x1C\x3\x1D\x5\x1D\x133\n\x1D\x3\x1D\x3\x1D\x3\x1E\x3"+
		"\x1E\x3\x1E\x3Z\x2\x2\x1F\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE\x2\x10\x2"+
		"\x12\x2\x14\x2\x16\x2\x18\x2\x1A\x2\x1C\x2\x1E\x2 \x2\"\x2$\x2&\x2(\x2"+
		"*\x2,\x2.\x2\x30\x2\x32\x2\x34\x2\x36\x2\x38\x2:\x2\x2\x5\x3\x2\x17\x18"+
		"\x3\x2\x1B\x1D\x3\x2\'*\x142\x2<\x3\x2\x2\x2\x4_\x3\x2\x2\x2\x6g\x3\x2"+
		"\x2\x2\bl\x3\x2\x2\x2\no\x3\x2\x2\x2\fr\x3\x2\x2\x2\xE\x84\x3\x2\x2\x2"+
		"\x10\x8C\x3\x2\x2\x2\x12\x94\x3\x2\x2\x2\x14\x97\x3\x2\x2\x2\x16\xA4\x3"+
		"\x2\x2\x2\x18\xAA\x3\x2\x2\x2\x1A\xAD\x3\x2\x2\x2\x1C\xBC\x3\x2\x2\x2"+
		"\x1E\xBF\x3\x2\x2\x2 \xC3\x3\x2\x2\x2\"\xDE\x3\x2\x2\x2$\xEC\x3\x2\x2"+
		"\x2&\x101\x3\x2\x2\x2(\x109\x3\x2\x2\x2*\x10C\x3\x2\x2\x2,\x10E\x3\x2"+
		"\x2\x2.\x112\x3\x2\x2\x2\x30\x119\x3\x2\x2\x2\x32\x125\x3\x2\x2\x2\x34"+
		"\x128\x3\x2\x2\x2\x36\x12D\x3\x2\x2\x2\x38\x132\x3\x2\x2\x2:\x136\x3\x2"+
		"\x2\x2<>\x5\x4\x3\x2=?\a\x32\x2\x2>=\x3\x2\x2\x2?@\x3\x2\x2\x2@>\x3\x2"+
		"\x2\x2@\x41\x3\x2\x2\x2\x41\x42\x3\x2\x2\x2\x42\x44\x5\xE\b\x2\x43\x45"+
		"\a\x32\x2\x2\x44\x43\x3\x2\x2\x2\x45\x46\x3\x2\x2\x2\x46\x44\x3\x2\x2"+
		"\x2\x46G\x3\x2\x2\x2GI\x3\x2\x2\x2HJ\x5\x12\n\x2IH\x3\x2\x2\x2JK\x3\x2"+
		"\x2\x2KI\x3\x2\x2\x2KL\x3\x2\x2\x2LN\x3\x2\x2\x2MO\a\x32\x2\x2NM\x3\x2"+
		"\x2\x2NO\x3\x2\x2\x2OQ\x3\x2\x2\x2PR\a\x32\x2\x2QP\x3\x2\x2\x2QR\x3\x2"+
		"\x2\x2RT\x3\x2\x2\x2SU\a\x32\x2\x2TS\x3\x2\x2\x2TU\x3\x2\x2\x2UV\x3\x2"+
		"\x2\x2VZ\x5\x10\t\x2WY\v\x2\x2\x2XW\x3\x2\x2\x2Y\\\x3\x2\x2\x2Z[\x3\x2"+
		"\x2\x2ZX\x3\x2\x2\x2[]\x3\x2\x2\x2\\Z\x3\x2\x2\x2]^\a\x2\x2\x3^\x3\x3"+
		"\x2\x2\x2_`\x5\x6\x4\x2`\x61\a\x32\x2\x2\x61\x62\x5\b\x5\x2\x62\x63\a"+
		"\x32\x2\x2\x63\x64\x5\n\x6\x2\x64\x65\a\x32\x2\x2\x65\x66\x5\f\a\x2\x66"+
		"\x5\x3\x2\x2\x2gh\a\f\x2\x2hj\a+\x2\x2ik\a+\x2\x2ji\x3\x2\x2\x2jk\x3\x2"+
		"\x2\x2k\a\x3\x2\x2\x2lm\a\r\x2\x2mn\a\xE\x2\x2n\t\x3\x2\x2\x2op\a\xF\x2"+
		"\x2pq\a+\x2\x2q\v\x3\x2\x2\x2rt\a\x10\x2\x2su\a+\x2\x2ts\x3\x2\x2\x2u"+
		"v\x3\x2\x2\x2vt\x3\x2\x2\x2vw\x3\x2\x2\x2w\x81\x3\x2\x2\x2xy\a,\x2\x2"+
		"y{\a\x32\x2\x2z|\a+\x2\x2{z\x3\x2\x2\x2|}\x3\x2\x2\x2}{\x3\x2\x2\x2}~"+
		"\x3\x2\x2\x2~\x80\x3\x2\x2\x2\x7Fx\x3\x2\x2\x2\x80\x83\x3\x2\x2\x2\x81"+
		"\x7F\x3\x2\x2\x2\x81\x82\x3\x2\x2\x2\x82\r\x3\x2\x2\x2\x83\x81\x3\x2\x2"+
		"\x2\x84\x85\a\x11\x2\x2\x85\x88\a+\x2\x2\x86\x87\a\x12\x2\x2\x87\x89\a"+
		"+\x2\x2\x88\x86\x3\x2\x2\x2\x88\x89\x3\x2\x2\x2\x89\x8A\x3\x2\x2\x2\x8A"+
		"\x8B\a\x30\x2\x2\x8B\xF\x3\x2\x2\x2\x8C\x8E\a\x13\x2\x2\x8D\x8F\a\x14"+
		"\x2\x2\x8E\x8D\x3\x2\x2\x2\x8E\x8F\x3\x2\x2\x2\x8F\x90\x3\x2\x2\x2\x90"+
		"\x91\a-\x2\x2\x91\x11\x3\x2\x2\x2\x92\x95\x5\x14\v\x2\x93\x95\x5\x16\f"+
		"\x2\x94\x92\x3\x2\x2\x2\x94\x93\x3\x2\x2\x2\x95\x13\x3\x2\x2\x2\x96\x98"+
		"\a\x31\x2\x2\x97\x96\x3\x2\x2\x2\x98\x99\x3\x2\x2\x2\x99\x97\x3\x2\x2"+
		"\x2\x99\x9A\x3\x2\x2\x2\x9A\x9E\x3\x2\x2\x2\x9B\x9F\x5\x18\r\x2\x9C\x9F"+
		"\x5\x1A\xE\x2\x9D\x9F\x5\x1C\xF\x2\x9E\x9B\x3\x2\x2\x2\x9E\x9C\x3\x2\x2"+
		"\x2\x9E\x9D\x3\x2\x2\x2\x9F\xA0\x3\x2\x2\x2\xA0\xA1\a-\x2\x2\xA1\xA2\a"+
		"\x32\x2\x2\xA2\x15\x3\x2\x2\x2\xA3\xA5\a\x31\x2\x2\xA4\xA3\x3\x2\x2\x2"+
		"\xA5\xA6\x3\x2\x2\x2\xA6\xA4\x3\x2\x2\x2\xA6\xA7\x3\x2\x2\x2\xA7\xA8\x3"+
		"\x2\x2\x2\xA8\xA9\x5 \x11\x2\xA9\x17\x3\x2\x2\x2\xAA\xAB\a\x3\x2\x2\xAB"+
		"\xAC\x5.\x18\x2\xAC\x19\x3\x2\x2\x2\xAD\xAE\a\x4\x2\x2\xAE\xB1\x5\x1E"+
		"\x10\x2\xAF\xB0\a\x5\x2\x2\xB0\xB2\x5.\x18\x2\xB1\xAF\x3\x2\x2\x2\xB1"+
		"\xB2\x3\x2\x2\x2\xB2\x1B\x3\x2\x2\x2\xB3\xB4\a\x6\x2\x2\xB4\xB5\x5.\x18"+
		"\x2\xB5\xB6\a\a\x2\x2\xB6\xB7\x5\x1E\x10\x2\xB7\xBD\x3\x2\x2\x2\xB8\xB9"+
		"\x5\x34\x1B\x2\xB9\xBA\a\x1F\x2\x2\xBA\xBB\x5.\x18\x2\xBB\xBD\x3\x2\x2"+
		"\x2\xBC\xB3\x3\x2\x2\x2\xBC\xB8\x3\x2\x2\x2\xBD\x1D\x3\x2\x2\x2\xBE\xC0"+
		"\a\x15\x2\x2\xBF\xBE\x3\x2\x2\x2\xBF\xC0\x3\x2\x2\x2\xC0\xC1\x3\x2\x2"+
		"\x2\xC1\xC2\a \x2\x2\xC2\x1F\x3\x2\x2\x2\xC3\xC4\a\b\x2\x2\xC4\xC5\x5"+
		"&\x14\x2\xC5\xC6\a\x16\x2\x2\xC6\xC8\a\x32\x2\x2\xC7\xC9\x5\x12\n\x2\xC8"+
		"\xC7\x3\x2\x2\x2\xC9\xCA\x3\x2\x2\x2\xCA\xC8\x3\x2\x2\x2\xCA\xCB\x3\x2"+
		"\x2\x2\xCB\xCF\x3\x2\x2\x2\xCC\xCE\x5\"\x12\x2\xCD\xCC\x3\x2\x2\x2\xCE"+
		"\xD1\x3\x2\x2\x2\xCF\xCD\x3\x2\x2\x2\xCF\xD0\x3\x2\x2\x2\xD0\xD3\x3\x2"+
		"\x2\x2\xD1\xCF\x3\x2\x2\x2\xD2\xD4\x5$\x13\x2\xD3\xD2\x3\x2\x2\x2\xD3"+
		"\xD4\x3\x2\x2\x2\xD4\xD6\x3\x2\x2\x2\xD5\xD7\a\x31\x2\x2\xD6\xD5\x3\x2"+
		"\x2\x2\xD7\xD8\x3\x2\x2\x2\xD8\xD6\x3\x2\x2\x2\xD8\xD9\x3\x2\x2\x2\xD9"+
		"\xDA\x3\x2\x2\x2\xDA\xDB\a.\x2\x2\xDB\xDC\a\x32\x2\x2\xDC!\x3\x2\x2\x2"+
		"\xDD\xDF\a\x31\x2\x2\xDE\xDD\x3\x2\x2\x2\xDF\xE0\x3\x2\x2\x2\xE0\xDE\x3"+
		"\x2\x2\x2\xE0\xE1\x3\x2\x2\x2\xE1\xE2\x3\x2\x2\x2\xE2\xE3\a\t\x2\x2\xE3"+
		"\xE4\x5&\x14\x2\xE4\xE5\a\x16\x2\x2\xE5\xE7\a\x32\x2\x2\xE6\xE8\x5\x12"+
		"\n\x2\xE7\xE6\x3\x2\x2\x2\xE8\xE9\x3\x2\x2\x2\xE9\xE7\x3\x2\x2\x2\xE9"+
		"\xEA\x3\x2\x2\x2\xEA#\x3\x2\x2\x2\xEB\xED\a\x31\x2\x2\xEC\xEB\x3\x2\x2"+
		"\x2\xED\xEE\x3\x2\x2\x2\xEE\xEC\x3\x2\x2\x2\xEE\xEF\x3\x2\x2\x2\xEF\xF0"+
		"\x3\x2\x2\x2\xF0\xF1\a\n\x2\x2\xF1\xF3\a\x32\x2\x2\xF2\xF4\x5\x12\n\x2"+
		"\xF3\xF2\x3\x2\x2\x2\xF4\xF5\x3\x2\x2\x2\xF5\xF3\x3\x2\x2\x2\xF5\xF6\x3"+
		"\x2\x2\x2\xF6%\x3\x2\x2\x2\xF7\xF8\x5.\x18\x2\xF8\xF9\x5*\x16\x2\xF9\xFA"+
		"\x5.\x18\x2\xFA\x102\x3\x2\x2\x2\xFB\xFC\a \x2\x2\xFC\xFD\a\x1E\x2\x2"+
		"\xFD\x100\a\x19\x2\x2\xFE\x100\a\x1A\x2\x2\xFF\xFB\x3\x2\x2\x2\xFF\xFE"+
		"\x3\x2\x2\x2\x100\x102\x3\x2\x2\x2\x101\xF7\x3\x2\x2\x2\x101\xFF\x3\x2"+
		"\x2\x2\x102\x106\x3\x2\x2\x2\x103\x105\x5(\x15\x2\x104\x103\x3\x2\x2\x2"+
		"\x105\x108\x3\x2\x2\x2\x106\x104\x3\x2\x2\x2\x106\x107\x3\x2\x2\x2\x107"+
		"\'\x3\x2\x2\x2\x108\x106\x3\x2\x2\x2\x109\x10A\x5,\x17\x2\x10A\x10B\x5"+
		"&\x14\x2\x10B)\x3\x2\x2\x2\x10C\x10D\t\x2\x2\x2\x10D+\x3\x2\x2\x2\x10E"+
		"\x10F\t\x3\x2\x2\x10F-\x3\x2\x2\x2\x110\x113\x5\x36\x1C\x2\x111\x113\x5"+
		"\x30\x19\x2\x112\x110\x3\x2\x2\x2\x112\x111\x3\x2\x2\x2\x113/\x3\x2\x2"+
		"\x2\x114\x11A\x5\x32\x1A\x2\x115\x116\a!\x2\x2\x116\x117\x5\x30\x19\x2"+
		"\x117\x118\a\"\x2\x2\x118\x11A\x3\x2\x2\x2\x119\x114\x3\x2\x2\x2\x119"+
		"\x115\x3\x2\x2\x2\x11A\x120\x3\x2\x2\x2\x11B\x11C\x5:\x1E\x2\x11C\x11D"+
		"\x5\x30\x19\x2\x11D\x11F\x3\x2\x2\x2\x11E\x11B\x3\x2\x2\x2\x11F\x122\x3"+
		"\x2\x2\x2\x120\x11E\x3\x2\x2\x2\x120\x121\x3\x2\x2\x2\x121\x31\x3\x2\x2"+
		"\x2\x122\x120\x3\x2\x2\x2\x123\x126\x5\x38\x1D\x2\x124\x126\x5\x34\x1B"+
		"\x2\x125\x123\x3\x2\x2\x2\x125\x124\x3\x2\x2\x2\x126\x33\x3\x2\x2\x2\x127"+
		"\x129\a\v\x2\x2\x128\x127\x3\x2\x2\x2\x128\x129\x3\x2\x2\x2\x129\x12A"+
		"\x3\x2\x2\x2\x12A\x12B\a \x2\x2\x12B\x35\x3\x2\x2\x2\x12C\x12E\a#\x2\x2"+
		"\x12D\x12C\x3\x2\x2\x2\x12D\x12E\x3\x2\x2\x2\x12E\x12F\x3\x2\x2\x2\x12F"+
		"\x130\a$\x2\x2\x130\x37\x3\x2\x2\x2\x131\x133\a%\x2\x2\x132\x131\x3\x2"+
		"\x2\x2\x132\x133\x3\x2\x2\x2\x133\x134\x3\x2\x2\x2\x134\x135\a&\x2\x2"+
		"\x135\x39\x3\x2\x2\x2\x136\x137\t\x4\x2\x2\x137;\x3\x2\x2\x2(@\x46KNQ"+
		"TZjv}\x81\x88\x8E\x94\x99\x9E\xA6\xB1\xBC\xBF\xCA\xCF\xD3\xD8\xE0\xE9"+
		"\xEE\xF5\xFF\x101\x106\x112\x119\x120\x125\x128\x12D\x132";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace interpreter.antlr
