//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/interpreter/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace interpreter.antlr {
#pragma warning disable 3021
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class CosmosParser : Parser {
	public const int
		LABEL_AUTEUR=1, LABEL_DATE=2, CONTENU_DATE=3, ENTREPRISE_ENTETE=4, DESCRIPTION_ENTETE=5, 
		TITRE=6, CONTEXTE=7, DEBUT=8, FIN=9, FONCTION_AFFICHER=10, DEBUT_CONDITION=11, 
		SUITE_CONDITION=12, ALTERNATIVE_CONDITION=13, OPERATEUR=14, OPERATEUR_EGAL=15, 
		OPERATEUR_DIFFERENT=16, LE_TEXTE=17, VALEUR_TEXTE=18, LE_NOMBRE=19, VALEUR_NOMBRE=20, 
		MOT=21, VIRGULE=22, POINT=23, TAB=24, RETCHAR=25, ESPACE=26, COMMENTAIRE_LIGNE=27, 
		COMMENTAIRE=28, NOOP=29;
	public const int
		RULE_programme = 0, RULE_entete = 1, RULE_auteur = 2, RULE_date = 3, RULE_entreprise = 4, 
		RULE_description = 5, RULE_contexte = 6, RULE_instruction_isolee = 7, 
		RULE_instruction_integree = 8, RULE_instruction_simple_base = 9, RULE_instruction_simple_isolee = 10, 
		RULE_instruction_simple_integree = 11, RULE_instruction_complexe_base = 12, 
		RULE_instruction_complexe_isolee = 13, RULE_instruction_complexe_integree = 14, 
		RULE_afficher = 15, RULE_selection = 16, RULE_condition = 17, RULE_expression_valeur = 18, 
		RULE_expression_textuelle = 19, RULE_expression_numeraire = 20;
	public static readonly string[] ruleNames = {
		"programme", "entete", "auteur", "date", "entreprise", "description", 
		"contexte", "instruction_isolee", "instruction_integree", "instruction_simple_base", 
		"instruction_simple_isolee", "instruction_simple_integree", "instruction_complexe_base", 
		"instruction_complexe_isolee", "instruction_complexe_integree", "afficher", 
		"selection", "condition", "expression_valeur", "expression_textuelle", 
		"expression_numeraire"
	};

	private static readonly string[] _LiteralNames = {
		null, "'Auteur:'", "'Date:'", null, "'Entreprise:'", "'Description:'", 
		null, null, "'Voici mes ordres:'", "'Fin.'", "'Afficher'", "'Si'", "'alors'", 
		"'sinon'", null, null, "'est différent de'", "'le texte'", null, null, 
		null, null, "','", "'.'"
	};
	private static readonly string[] _SymbolicNames = {
		null, "LABEL_AUTEUR", "LABEL_DATE", "CONTENU_DATE", "ENTREPRISE_ENTETE", 
		"DESCRIPTION_ENTETE", "TITRE", "CONTEXTE", "DEBUT", "FIN", "FONCTION_AFFICHER", 
		"DEBUT_CONDITION", "SUITE_CONDITION", "ALTERNATIVE_CONDITION", "OPERATEUR", 
		"OPERATEUR_EGAL", "OPERATEUR_DIFFERENT", "LE_TEXTE", "VALEUR_TEXTE", "LE_NOMBRE", 
		"VALEUR_NOMBRE", "MOT", "VIRGULE", "POINT", "TAB", "RETCHAR", "ESPACE", 
		"COMMENTAIRE_LIGNE", "COMMENTAIRE", "NOOP"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete("Use IRecognizer.Vocabulary instead.")]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Cosmos.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public CosmosParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class ProgrammeContext : ParserRuleContext {
		public EnteteContext entete() {
			return GetRuleContext<EnteteContext>(0);
		}
		public ITerminalNode DEBUT() { return GetToken(CosmosParser.DEBUT, 0); }
		public ITerminalNode FIN() { return GetToken(CosmosParser.FIN, 0); }
		public ITerminalNode Eof() { return GetToken(CosmosParser.Eof, 0); }
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public ContexteContext contexte() {
			return GetRuleContext<ContexteContext>(0);
		}
		public Instruction_isoleeContext[] instruction_isolee() {
			return GetRuleContexts<Instruction_isoleeContext>();
		}
		public Instruction_isoleeContext instruction_isolee(int i) {
			return GetRuleContext<Instruction_isoleeContext>(i);
		}
		public ProgrammeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_programme; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterProgramme(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitProgramme(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitProgramme(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ProgrammeContext programme() {
		ProgrammeContext _localctx = new ProgrammeContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_programme);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 42; entete();
			State = 44;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 43; Match(RETCHAR);
				}
				}
				State = 46;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==RETCHAR );
			State = 54;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==CONTEXTE) {
				{
				State = 48; contexte();
				State = 50;
				_errHandler.Sync(this);
				_la = _input.La(1);
				do {
					{
					{
					State = 49; Match(RETCHAR);
					}
					}
					State = 52;
					_errHandler.Sync(this);
					_la = _input.La(1);
				} while ( _la==RETCHAR );
				}
			}

			State = 56; Match(DEBUT);
			State = 58;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 57; Match(RETCHAR);
				}
				}
				State = 60;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==RETCHAR );
			State = 63;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 62; instruction_isolee();
				}
				}
				State = 65;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 67; Match(FIN);
			State = 68; Match(Eof);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnteteContext : ParserRuleContext {
		public AuteurContext auteur() {
			return GetRuleContext<AuteurContext>(0);
		}
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public DateContext date() {
			return GetRuleContext<DateContext>(0);
		}
		public EntrepriseContext entreprise() {
			return GetRuleContext<EntrepriseContext>(0);
		}
		public DescriptionContext description() {
			return GetRuleContext<DescriptionContext>(0);
		}
		public EnteteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entete; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterEntete(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitEntete(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntete(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnteteContext entete() {
		EnteteContext _localctx = new EnteteContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_entete);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 70; auteur();
			State = 71; Match(RETCHAR);
			State = 72; date();
			State = 73; Match(RETCHAR);
			State = 74; entreprise();
			State = 75; Match(RETCHAR);
			State = 76; description();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AuteurContext : ParserRuleContext {
		public ITerminalNode LABEL_AUTEUR() { return GetToken(CosmosParser.LABEL_AUTEUR, 0); }
		public ITerminalNode[] MOT() { return GetTokens(CosmosParser.MOT); }
		public ITerminalNode MOT(int i) {
			return GetToken(CosmosParser.MOT, i);
		}
		public AuteurContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_auteur; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterAuteur(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitAuteur(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAuteur(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AuteurContext auteur() {
		AuteurContext _localctx = new AuteurContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_auteur);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 78; Match(LABEL_AUTEUR);
			State = 79; Match(MOT);
			State = 81;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==MOT) {
				{
				State = 80; Match(MOT);
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DateContext : ParserRuleContext {
		public ITerminalNode LABEL_DATE() { return GetToken(CosmosParser.LABEL_DATE, 0); }
		public ITerminalNode CONTENU_DATE() { return GetToken(CosmosParser.CONTENU_DATE, 0); }
		public DateContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_date; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterDate(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitDate(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDate(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DateContext date() {
		DateContext _localctx = new DateContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_date);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 83; Match(LABEL_DATE);
			State = 84; Match(CONTENU_DATE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EntrepriseContext : ParserRuleContext {
		public ITerminalNode ENTREPRISE_ENTETE() { return GetToken(CosmosParser.ENTREPRISE_ENTETE, 0); }
		public ITerminalNode MOT() { return GetToken(CosmosParser.MOT, 0); }
		public EntrepriseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_entreprise; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterEntreprise(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitEntreprise(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEntreprise(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EntrepriseContext entreprise() {
		EntrepriseContext _localctx = new EntrepriseContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_entreprise);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 86; Match(ENTREPRISE_ENTETE);
			State = 87; Match(MOT);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DescriptionContext : ParserRuleContext {
		public ITerminalNode DESCRIPTION_ENTETE() { return GetToken(CosmosParser.DESCRIPTION_ENTETE, 0); }
		public ITerminalNode[] MOT() { return GetTokens(CosmosParser.MOT); }
		public ITerminalNode MOT(int i) {
			return GetToken(CosmosParser.MOT, i);
		}
		public ITerminalNode[] VIRGULE() { return GetTokens(CosmosParser.VIRGULE); }
		public ITerminalNode VIRGULE(int i) {
			return GetToken(CosmosParser.VIRGULE, i);
		}
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public DescriptionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_description; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterDescription(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitDescription(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDescription(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DescriptionContext description() {
		DescriptionContext _localctx = new DescriptionContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_description);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 89; Match(DESCRIPTION_ENTETE);
			State = 91;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 90; Match(MOT);
				}
				}
				State = 93;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==MOT );
			State = 104;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==VIRGULE) {
				{
				{
				State = 95; Match(VIRGULE);
				State = 96; Match(RETCHAR);
				State = 98;
				_errHandler.Sync(this);
				_la = _input.La(1);
				do {
					{
					{
					State = 97; Match(MOT);
					}
					}
					State = 100;
					_errHandler.Sync(this);
					_la = _input.La(1);
				} while ( _la==MOT );
				}
				}
				State = 106;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ContexteContext : ParserRuleContext {
		public ITerminalNode CONTEXTE() { return GetToken(CosmosParser.CONTEXTE, 0); }
		public ITerminalNode TITRE() { return GetToken(CosmosParser.TITRE, 0); }
		public ITerminalNode[] RETCHAR() { return GetTokens(CosmosParser.RETCHAR); }
		public ITerminalNode RETCHAR(int i) {
			return GetToken(CosmosParser.RETCHAR, i);
		}
		public ContexteContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_contexte; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterContexte(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitContexte(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitContexte(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ContexteContext contexte() {
		ContexteContext _localctx = new ContexteContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_contexte);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 107; Match(CONTEXTE);
			State = 109;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 108; Match(RETCHAR);
				}
				}
				State = 111;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==RETCHAR );
			State = 113; Match(TITRE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_isoleeContext : ParserRuleContext {
		public Instruction_simple_isoleeContext instruction_simple_isolee() {
			return GetRuleContext<Instruction_simple_isoleeContext>(0);
		}
		public Instruction_complexe_isoleeContext instruction_complexe_isolee() {
			return GetRuleContext<Instruction_complexe_isoleeContext>(0);
		}
		public Instruction_isoleeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_isolee; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_isolee(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_isolee(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_isolee(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_isoleeContext instruction_isolee() {
		Instruction_isoleeContext _localctx = new Instruction_isoleeContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_instruction_isolee);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 117;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,10,_ctx) ) {
			case 1:
				{
				State = 115; instruction_simple_isolee();
				}
				break;

			case 2:
				{
				State = 116; instruction_complexe_isolee();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_integreeContext : ParserRuleContext {
		public Instruction_simple_integreeContext instruction_simple_integree() {
			return GetRuleContext<Instruction_simple_integreeContext>(0);
		}
		public Instruction_complexe_integreeContext instruction_complexe_integree() {
			return GetRuleContext<Instruction_complexe_integreeContext>(0);
		}
		public Instruction_integreeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_integree; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_integree(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_integree(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_integree(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_integreeContext instruction_integree() {
		Instruction_integreeContext _localctx = new Instruction_integreeContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_instruction_integree);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 121;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,11,_ctx) ) {
			case 1:
				{
				State = 119; instruction_simple_integree();
				}
				break;

			case 2:
				{
				State = 120; instruction_complexe_integree();
				}
				break;
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_simple_baseContext : ParserRuleContext {
		public AfficherContext afficher() {
			return GetRuleContext<AfficherContext>(0);
		}
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public Instruction_simple_baseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_simple_base; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_simple_base(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_simple_base(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_simple_base(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_simple_baseContext instruction_simple_base() {
		Instruction_simple_baseContext _localctx = new Instruction_simple_baseContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_instruction_simple_base);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 124;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 123; Match(TAB);
				}
				}
				State = 126;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			{
			State = 128; afficher();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_simple_isoleeContext : ParserRuleContext {
		public Instruction_simple_baseContext instruction_simple_base() {
			return GetRuleContext<Instruction_simple_baseContext>(0);
		}
		public ITerminalNode POINT() { return GetToken(CosmosParser.POINT, 0); }
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public Instruction_simple_isoleeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_simple_isolee; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_simple_isolee(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_simple_isolee(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_simple_isolee(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_simple_isoleeContext instruction_simple_isolee() {
		Instruction_simple_isoleeContext _localctx = new Instruction_simple_isoleeContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_instruction_simple_isolee);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 130; instruction_simple_base();
			State = 131; Match(POINT);
			State = 132; Match(RETCHAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_simple_integreeContext : ParserRuleContext {
		public Instruction_simple_baseContext instruction_simple_base() {
			return GetRuleContext<Instruction_simple_baseContext>(0);
		}
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public ITerminalNode VIRGULE() { return GetToken(CosmosParser.VIRGULE, 0); }
		public Instruction_simple_integreeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_simple_integree; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_simple_integree(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_simple_integree(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_simple_integree(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_simple_integreeContext instruction_simple_integree() {
		Instruction_simple_integreeContext _localctx = new Instruction_simple_integreeContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_instruction_simple_integree);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134; instruction_simple_base();
			State = 136;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==VIRGULE) {
				{
				State = 135; Match(VIRGULE);
				}
			}

			State = 138; Match(RETCHAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_complexe_baseContext : ParserRuleContext {
		public SelectionContext selection() {
			return GetRuleContext<SelectionContext>(0);
		}
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public Instruction_complexe_baseContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_complexe_base; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_complexe_base(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_complexe_base(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_complexe_base(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_complexe_baseContext instruction_complexe_base() {
		Instruction_complexe_baseContext _localctx = new Instruction_complexe_baseContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_instruction_complexe_base);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 141;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 140; Match(TAB);
				}
				}
				State = 143;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			{
			State = 145; selection();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_complexe_isoleeContext : ParserRuleContext {
		public Instruction_complexe_baseContext instruction_complexe_base() {
			return GetRuleContext<Instruction_complexe_baseContext>(0);
		}
		public ITerminalNode POINT() { return GetToken(CosmosParser.POINT, 0); }
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public Instruction_complexe_isoleeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_complexe_isolee; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_complexe_isolee(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_complexe_isolee(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_complexe_isolee(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_complexe_isoleeContext instruction_complexe_isolee() {
		Instruction_complexe_isoleeContext _localctx = new Instruction_complexe_isoleeContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_instruction_complexe_isolee);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 147; instruction_complexe_base();
			State = 149;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 148; Match(TAB);
				}
				}
				State = 151;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 153; Match(POINT);
			State = 154; Match(RETCHAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Instruction_complexe_integreeContext : ParserRuleContext {
		public Instruction_complexe_baseContext instruction_complexe_base() {
			return GetRuleContext<Instruction_complexe_baseContext>(0);
		}
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public ITerminalNode[] TAB() { return GetTokens(CosmosParser.TAB); }
		public ITerminalNode TAB(int i) {
			return GetToken(CosmosParser.TAB, i);
		}
		public ITerminalNode VIRGULE() { return GetToken(CosmosParser.VIRGULE, 0); }
		public Instruction_complexe_integreeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_instruction_complexe_integree; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterInstruction_complexe_integree(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitInstruction_complexe_integree(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInstruction_complexe_integree(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Instruction_complexe_integreeContext instruction_complexe_integree() {
		Instruction_complexe_integreeContext _localctx = new Instruction_complexe_integreeContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_instruction_complexe_integree);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 156; instruction_complexe_base();
			State = 158;
			_errHandler.Sync(this);
			_la = _input.La(1);
			do {
				{
				{
				State = 157; Match(TAB);
				}
				}
				State = 160;
				_errHandler.Sync(this);
				_la = _input.La(1);
			} while ( _la==TAB );
			State = 163;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==VIRGULE) {
				{
				State = 162; Match(VIRGULE);
				}
			}

			State = 165; Match(RETCHAR);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AfficherContext : ParserRuleContext {
		public ITerminalNode FONCTION_AFFICHER() { return GetToken(CosmosParser.FONCTION_AFFICHER, 0); }
		public Expression_valeurContext expression_valeur() {
			return GetRuleContext<Expression_valeurContext>(0);
		}
		public AfficherContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_afficher; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterAfficher(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitAfficher(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAfficher(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AfficherContext afficher() {
		AfficherContext _localctx = new AfficherContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_afficher);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 167; Match(FONCTION_AFFICHER);
			State = 168; expression_valeur();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SelectionContext : ParserRuleContext {
		public ITerminalNode DEBUT_CONDITION() { return GetToken(CosmosParser.DEBUT_CONDITION, 0); }
		public ConditionContext condition() {
			return GetRuleContext<ConditionContext>(0);
		}
		public ITerminalNode SUITE_CONDITION() { return GetToken(CosmosParser.SUITE_CONDITION, 0); }
		public ITerminalNode RETCHAR() { return GetToken(CosmosParser.RETCHAR, 0); }
		public Instruction_integreeContext[] instruction_integree() {
			return GetRuleContexts<Instruction_integreeContext>();
		}
		public Instruction_integreeContext instruction_integree(int i) {
			return GetRuleContext<Instruction_integreeContext>(i);
		}
		public SelectionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_selection; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterSelection(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitSelection(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSelection(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SelectionContext selection() {
		SelectionContext _localctx = new SelectionContext(_ctx, State);
		EnterRule(_localctx, 32, RULE_selection);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 170; Match(DEBUT_CONDITION);
			State = 171; condition();
			State = 172; Match(SUITE_CONDITION);
			State = 173; Match(RETCHAR);
			State = 175;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 174; instruction_integree();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 177;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,18,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConditionContext : ParserRuleContext {
		public Expression_valeurContext[] expression_valeur() {
			return GetRuleContexts<Expression_valeurContext>();
		}
		public Expression_valeurContext expression_valeur(int i) {
			return GetRuleContext<Expression_valeurContext>(i);
		}
		public ITerminalNode OPERATEUR() { return GetToken(CosmosParser.OPERATEUR, 0); }
		public ConditionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_condition; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterCondition(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitCondition(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCondition(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConditionContext condition() {
		ConditionContext _localctx = new ConditionContext(_ctx, State);
		EnterRule(_localctx, 34, RULE_condition);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 179; expression_valeur();
			State = 180; Match(OPERATEUR);
			State = 181; expression_valeur();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_valeurContext : ParserRuleContext {
		public Expression_textuelleContext expression_textuelle() {
			return GetRuleContext<Expression_textuelleContext>(0);
		}
		public Expression_numeraireContext expression_numeraire() {
			return GetRuleContext<Expression_numeraireContext>(0);
		}
		public Expression_valeurContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_valeur; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_valeur(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_valeur(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_valeur(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_valeurContext expression_valeur() {
		Expression_valeurContext _localctx = new Expression_valeurContext(_ctx, State);
		EnterRule(_localctx, 36, RULE_expression_valeur);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 185;
			_errHandler.Sync(this);
			switch (_input.La(1)) {
			case LE_TEXTE:
			case VALEUR_TEXTE:
				{
				State = 183; expression_textuelle();
				}
				break;
			case LE_NOMBRE:
			case VALEUR_NOMBRE:
				{
				State = 184; expression_numeraire();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_textuelleContext : ParserRuleContext {
		public ITerminalNode VALEUR_TEXTE() { return GetToken(CosmosParser.VALEUR_TEXTE, 0); }
		public ITerminalNode LE_TEXTE() { return GetToken(CosmosParser.LE_TEXTE, 0); }
		public Expression_textuelleContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_textuelle; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_textuelle(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_textuelle(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_textuelle(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_textuelleContext expression_textuelle() {
		Expression_textuelleContext _localctx = new Expression_textuelleContext(_ctx, State);
		EnterRule(_localctx, 38, RULE_expression_textuelle);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 188;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LE_TEXTE) {
				{
				State = 187; Match(LE_TEXTE);
				}
			}

			State = 190; Match(VALEUR_TEXTE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Expression_numeraireContext : ParserRuleContext {
		public ITerminalNode VALEUR_NOMBRE() { return GetToken(CosmosParser.VALEUR_NOMBRE, 0); }
		public ITerminalNode LE_NOMBRE() { return GetToken(CosmosParser.LE_NOMBRE, 0); }
		public Expression_numeraireContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_expression_numeraire; } }
		public override void EnterRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.EnterExpression_numeraire(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ICosmosListener typedListener = listener as ICosmosListener;
			if (typedListener != null) typedListener.ExitExpression_numeraire(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ICosmosVisitor<TResult> typedVisitor = visitor as ICosmosVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExpression_numeraire(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public Expression_numeraireContext expression_numeraire() {
		Expression_numeraireContext _localctx = new Expression_numeraireContext(_ctx, State);
		EnterRule(_localctx, 40, RULE_expression_numeraire);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 193;
			_errHandler.Sync(this);
			_la = _input.La(1);
			if (_la==LE_NOMBRE) {
				{
				State = 192; Match(LE_NOMBRE);
				}
			}

			State = 195; Match(VALEUR_NOMBRE);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\x1F\xC8\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x3\x2\x3\x2\x6\x2/\n\x2\r\x2\xE\x2\x30\x3\x2\x3\x2\x6\x2"+
		"\x35\n\x2\r\x2\xE\x2\x36\x5\x2\x39\n\x2\x3\x2\x3\x2\x6\x2=\n\x2\r\x2\xE"+
		"\x2>\x3\x2\x6\x2\x42\n\x2\r\x2\xE\x2\x43\x3\x2\x3\x2\x3\x2\x3\x3\x3\x3"+
		"\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x3\x4\x3\x4\x3\x4\x5\x4T\n\x4\x3"+
		"\x5\x3\x5\x3\x5\x3\x6\x3\x6\x3\x6\x3\a\x3\a\x6\a^\n\a\r\a\xE\a_\x3\a\x3"+
		"\a\x3\a\x6\a\x65\n\a\r\a\xE\a\x66\a\ai\n\a\f\a\xE\al\v\a\x3\b\x3\b\x6"+
		"\bp\n\b\r\b\xE\bq\x3\b\x3\b\x3\t\x3\t\x5\tx\n\t\x3\n\x3\n\x5\n|\n\n\x3"+
		"\v\x6\v\x7F\n\v\r\v\xE\v\x80\x3\v\x3\v\x3\f\x3\f\x3\f\x3\f\x3\r\x3\r\x5"+
		"\r\x8B\n\r\x3\r\x3\r\x3\xE\x6\xE\x90\n\xE\r\xE\xE\xE\x91\x3\xE\x3\xE\x3"+
		"\xF\x3\xF\x6\xF\x98\n\xF\r\xF\xE\xF\x99\x3\xF\x3\xF\x3\xF\x3\x10\x3\x10"+
		"\x6\x10\xA1\n\x10\r\x10\xE\x10\xA2\x3\x10\x5\x10\xA6\n\x10\x3\x10\x3\x10"+
		"\x3\x11\x3\x11\x3\x11\x3\x12\x3\x12\x3\x12\x3\x12\x3\x12\x6\x12\xB2\n"+
		"\x12\r\x12\xE\x12\xB3\x3\x13\x3\x13\x3\x13\x3\x13\x3\x14\x3\x14\x5\x14"+
		"\xBC\n\x14\x3\x15\x5\x15\xBF\n\x15\x3\x15\x3\x15\x3\x16\x5\x16\xC4\n\x16"+
		"\x3\x16\x3\x16\x3\x16\x2\x2\x2\x17\x2\x2\x4\x2\x6\x2\b\x2\n\x2\f\x2\xE"+
		"\x2\x10\x2\x12\x2\x14\x2\x16\x2\x18\x2\x1A\x2\x1C\x2\x1E\x2 \x2\"\x2$"+
		"\x2&\x2(\x2*\x2\x2\x2\xC8\x2,\x3\x2\x2\x2\x4H\x3\x2\x2\x2\x6P\x3\x2\x2"+
		"\x2\bU\x3\x2\x2\x2\nX\x3\x2\x2\x2\f[\x3\x2\x2\x2\xEm\x3\x2\x2\x2\x10w"+
		"\x3\x2\x2\x2\x12{\x3\x2\x2\x2\x14~\x3\x2\x2\x2\x16\x84\x3\x2\x2\x2\x18"+
		"\x88\x3\x2\x2\x2\x1A\x8F\x3\x2\x2\x2\x1C\x95\x3\x2\x2\x2\x1E\x9E\x3\x2"+
		"\x2\x2 \xA9\x3\x2\x2\x2\"\xAC\x3\x2\x2\x2$\xB5\x3\x2\x2\x2&\xBB\x3\x2"+
		"\x2\x2(\xBE\x3\x2\x2\x2*\xC3\x3\x2\x2\x2,.\x5\x4\x3\x2-/\a\x1B\x2\x2."+
		"-\x3\x2\x2\x2/\x30\x3\x2\x2\x2\x30.\x3\x2\x2\x2\x30\x31\x3\x2\x2\x2\x31"+
		"\x38\x3\x2\x2\x2\x32\x34\x5\xE\b\x2\x33\x35\a\x1B\x2\x2\x34\x33\x3\x2"+
		"\x2\x2\x35\x36\x3\x2\x2\x2\x36\x34\x3\x2\x2\x2\x36\x37\x3\x2\x2\x2\x37"+
		"\x39\x3\x2\x2\x2\x38\x32\x3\x2\x2\x2\x38\x39\x3\x2\x2\x2\x39:\x3\x2\x2"+
		"\x2:<\a\n\x2\x2;=\a\x1B\x2\x2<;\x3\x2\x2\x2=>\x3\x2\x2\x2><\x3\x2\x2\x2"+
		">?\x3\x2\x2\x2?\x41\x3\x2\x2\x2@\x42\x5\x10\t\x2\x41@\x3\x2\x2\x2\x42"+
		"\x43\x3\x2\x2\x2\x43\x41\x3\x2\x2\x2\x43\x44\x3\x2\x2\x2\x44\x45\x3\x2"+
		"\x2\x2\x45\x46\a\v\x2\x2\x46G\a\x2\x2\x3G\x3\x3\x2\x2\x2HI\x5\x6\x4\x2"+
		"IJ\a\x1B\x2\x2JK\x5\b\x5\x2KL\a\x1B\x2\x2LM\x5\n\x6\x2MN\a\x1B\x2\x2N"+
		"O\x5\f\a\x2O\x5\x3\x2\x2\x2PQ\a\x3\x2\x2QS\a\x17\x2\x2RT\a\x17\x2\x2S"+
		"R\x3\x2\x2\x2ST\x3\x2\x2\x2T\a\x3\x2\x2\x2UV\a\x4\x2\x2VW\a\x5\x2\x2W"+
		"\t\x3\x2\x2\x2XY\a\x6\x2\x2YZ\a\x17\x2\x2Z\v\x3\x2\x2\x2[]\a\a\x2\x2\\"+
		"^\a\x17\x2\x2]\\\x3\x2\x2\x2^_\x3\x2\x2\x2_]\x3\x2\x2\x2_`\x3\x2\x2\x2"+
		"`j\x3\x2\x2\x2\x61\x62\a\x18\x2\x2\x62\x64\a\x1B\x2\x2\x63\x65\a\x17\x2"+
		"\x2\x64\x63\x3\x2\x2\x2\x65\x66\x3\x2\x2\x2\x66\x64\x3\x2\x2\x2\x66g\x3"+
		"\x2\x2\x2gi\x3\x2\x2\x2h\x61\x3\x2\x2\x2il\x3\x2\x2\x2jh\x3\x2\x2\x2j"+
		"k\x3\x2\x2\x2k\r\x3\x2\x2\x2lj\x3\x2\x2\x2mo\a\t\x2\x2np\a\x1B\x2\x2o"+
		"n\x3\x2\x2\x2pq\x3\x2\x2\x2qo\x3\x2\x2\x2qr\x3\x2\x2\x2rs\x3\x2\x2\x2"+
		"st\a\b\x2\x2t\xF\x3\x2\x2\x2ux\x5\x16\f\x2vx\x5\x1C\xF\x2wu\x3\x2\x2\x2"+
		"wv\x3\x2\x2\x2x\x11\x3\x2\x2\x2y|\x5\x18\r\x2z|\x5\x1E\x10\x2{y\x3\x2"+
		"\x2\x2{z\x3\x2\x2\x2|\x13\x3\x2\x2\x2}\x7F\a\x1A\x2\x2~}\x3\x2\x2\x2\x7F"+
		"\x80\x3\x2\x2\x2\x80~\x3\x2\x2\x2\x80\x81\x3\x2\x2\x2\x81\x82\x3\x2\x2"+
		"\x2\x82\x83\x5 \x11\x2\x83\x15\x3\x2\x2\x2\x84\x85\x5\x14\v\x2\x85\x86"+
		"\a\x19\x2\x2\x86\x87\a\x1B\x2\x2\x87\x17\x3\x2\x2\x2\x88\x8A\x5\x14\v"+
		"\x2\x89\x8B\a\x18\x2\x2\x8A\x89\x3\x2\x2\x2\x8A\x8B\x3\x2\x2\x2\x8B\x8C"+
		"\x3\x2\x2\x2\x8C\x8D\a\x1B\x2\x2\x8D\x19\x3\x2\x2\x2\x8E\x90\a\x1A\x2"+
		"\x2\x8F\x8E\x3\x2\x2\x2\x90\x91\x3\x2\x2\x2\x91\x8F\x3\x2\x2\x2\x91\x92"+
		"\x3\x2\x2\x2\x92\x93\x3\x2\x2\x2\x93\x94\x5\"\x12\x2\x94\x1B\x3\x2\x2"+
		"\x2\x95\x97\x5\x1A\xE\x2\x96\x98\a\x1A\x2\x2\x97\x96\x3\x2\x2\x2\x98\x99"+
		"\x3\x2\x2\x2\x99\x97\x3\x2\x2\x2\x99\x9A\x3\x2\x2\x2\x9A\x9B\x3\x2\x2"+
		"\x2\x9B\x9C\a\x19\x2\x2\x9C\x9D\a\x1B\x2\x2\x9D\x1D\x3\x2\x2\x2\x9E\xA0"+
		"\x5\x1A\xE\x2\x9F\xA1\a\x1A\x2\x2\xA0\x9F\x3\x2\x2\x2\xA1\xA2\x3\x2\x2"+
		"\x2\xA2\xA0\x3\x2\x2\x2\xA2\xA3\x3\x2\x2\x2\xA3\xA5\x3\x2\x2\x2\xA4\xA6"+
		"\a\x18\x2\x2\xA5\xA4\x3\x2\x2\x2\xA5\xA6\x3\x2\x2\x2\xA6\xA7\x3\x2\x2"+
		"\x2\xA7\xA8\a\x1B\x2\x2\xA8\x1F\x3\x2\x2\x2\xA9\xAA\a\f\x2\x2\xAA\xAB"+
		"\x5&\x14\x2\xAB!\x3\x2\x2\x2\xAC\xAD\a\r\x2\x2\xAD\xAE\x5$\x13\x2\xAE"+
		"\xAF\a\xE\x2\x2\xAF\xB1\a\x1B\x2\x2\xB0\xB2\x5\x12\n\x2\xB1\xB0\x3\x2"+
		"\x2\x2\xB2\xB3\x3\x2\x2\x2\xB3\xB1\x3\x2\x2\x2\xB3\xB4\x3\x2\x2\x2\xB4"+
		"#\x3\x2\x2\x2\xB5\xB6\x5&\x14\x2\xB6\xB7\a\x10\x2\x2\xB7\xB8\x5&\x14\x2"+
		"\xB8%\x3\x2\x2\x2\xB9\xBC\x5(\x15\x2\xBA\xBC\x5*\x16\x2\xBB\xB9\x3\x2"+
		"\x2\x2\xBB\xBA\x3\x2\x2\x2\xBC\'\x3\x2\x2\x2\xBD\xBF\a\x13\x2\x2\xBE\xBD"+
		"\x3\x2\x2\x2\xBE\xBF\x3\x2\x2\x2\xBF\xC0\x3\x2\x2\x2\xC0\xC1\a\x14\x2"+
		"\x2\xC1)\x3\x2\x2\x2\xC2\xC4\a\x15\x2\x2\xC3\xC2\x3\x2\x2\x2\xC3\xC4\x3"+
		"\x2\x2\x2\xC4\xC5\x3\x2\x2\x2\xC5\xC6\a\x16\x2\x2\xC6+\x3\x2\x2\x2\x18"+
		"\x30\x36\x38>\x43S_\x66jqw{\x80\x8A\x91\x99\xA2\xA5\xB3\xBB\xBE\xC3";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace interpreter.antlr
