//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/interpreter/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace interpreter.antlr {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CosmosParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ICosmosVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.programme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramme([NotNull] CosmosParser.ProgrammeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.entete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntete([NotNull] CosmosParser.EnteteContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.auteur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuteur([NotNull] CosmosParser.AuteurContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] CosmosParser.DateContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.entreprise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntreprise([NotNull] CosmosParser.EntrepriseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescription([NotNull] CosmosParser.DescriptionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.contexte"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContexte([NotNull] CosmosParser.ContexteContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_isolee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_isolee([NotNull] CosmosParser.Instruction_isoleeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_integree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_integree([NotNull] CosmosParser.Instruction_integreeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_simple_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_simple_base([NotNull] CosmosParser.Instruction_simple_baseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_simple_isolee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_simple_isolee([NotNull] CosmosParser.Instruction_simple_isoleeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_simple_integree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_simple_integree([NotNull] CosmosParser.Instruction_simple_integreeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_complexe_base"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_complexe_base([NotNull] CosmosParser.Instruction_complexe_baseContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_complexe_isolee"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_complexe_isolee([NotNull] CosmosParser.Instruction_complexe_isoleeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_complexe_integree"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_complexe_integree([NotNull] CosmosParser.Instruction_complexe_integreeContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.afficher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAfficher([NotNull] CosmosParser.AfficherContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection([NotNull] CosmosParser.SelectionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] CosmosParser.ConditionContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.operateur_comparaison"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOperateur_comparaison([NotNull] CosmosParser.Operateur_comparaisonContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_valeur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_valeur([NotNull] CosmosParser.Expression_valeurContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_textuelle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_textuelle([NotNull] CosmosParser.Expression_textuelleContext context);

	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_numeraire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_numeraire([NotNull] CosmosParser.Expression_numeraireContext context);
}
} // namespace interpreter.antlr
