#creates artifacts on version tag
name: '$(TeamProject)-$(BuildDefinitionName)[$(SourceBranchName)] du $(Date:dd.MM.yyyy) a $(Date:HH)h$(Date:mm)m$(Date:ss)s'

# Triggers on release/* tag on release branch only
trigger:
  tags:
    include:
      - release/*
    exclude:
      - master
      - integration
      - change/*

variables:
  - template: variables.yml

stages:

  - template: platform-stage-tmpl.yml
    parameters:
      name: LinuxArtifacts
      steps:
        - template: cd-publish-tmpl.yml
          parameters:
            runtime: $(runtime_linux)
            includeNotesTemplate: true

  - template: platform-stage-tmpl.yml
    parameters:
      name: MacArtifacts
      steps:
        - template: cd-publish-tmpl.yml
          parameters:
            runtime: $(runtime_mac)

  - template: platform-stage-tmpl.yml
    parameters:
      name: WindowsArtifacts
      steps:
        - template: cd-publish-tmpl.yml
          parameters:
            runtime: $(runtime_windows)
