#Linux executor
parameters:
  - name: dependsOn
    type: object
    default: {}
  - name: steps
    type: stepList
    default: []

stages:
  - stage: Linux
    dependsOn:
    - ${{ parameters.dependsOn }}
    pool:
      vmImage: $(vm_linux)
    jobs:
      - job: Steps
        steps:
        - ${{ parameters.steps }}