//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/lib/../grammar/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lib.antlr {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="Cosmos"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ICosmosVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.programme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramme([NotNull] Cosmos.ProgrammeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.entete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntete([NotNull] Cosmos.EnteteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.auteur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuteur([NotNull] Cosmos.AuteurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] Cosmos.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.entreprise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntreprise([NotNull] Cosmos.EntrepriseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescription([NotNull] Cosmos.DescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.mainStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainStart([NotNull] Cosmos.MainStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.mainEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainEnd([NotNull] Cosmos.MainEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] Cosmos.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.noop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoop([NotNull] Cosmos.NoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.instruction_simple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_simple([NotNull] Cosmos.Instruction_simpleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.instruction_complexe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_complexe([NotNull] Cosmos.Instruction_complexeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.afficher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAfficher([NotNull] Cosmos.AfficherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.allouer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllouer([NotNull] Cosmos.AllouerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.affecter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAffecter([NotNull] Cosmos.AffecterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.recuperer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecuperer([NotNull] Cosmos.RecupererContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.placer_curseur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlacer_curseur([NotNull] Cosmos.Placer_curseurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.generer_aleatoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerer_aleatoire([NotNull] Cosmos.Generer_aleatoireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.dormir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDormir([NotNull] Cosmos.DormirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.colorier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColorier([NotNull] Cosmos.ColorierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.decouper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDecouper([NotNull] Cosmos.DecouperContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.afficher_curseur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAfficher_curseur([NotNull] Cosmos.Afficher_curseurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.masquer_curseur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMasquer_curseur([NotNull] Cosmos.Masquer_curseurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.lire_touche"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLire_touche([NotNull] Cosmos.Lire_toucheContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] Cosmos.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.la_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLa_zone_memoire([NotNull] Cosmos.La_zone_memoireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.une_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUne_zone_memoire([NotNull] Cosmos.Une_zone_memoireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.boucle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoucle([NotNull] Cosmos.BoucleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.boucle_avec_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoucle_avec_variable([NotNull] Cosmos.Boucle_avec_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection([NotNull] Cosmos.SelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.base_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_si([NotNull] Cosmos.Base_siContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.sinon_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinon_si([NotNull] Cosmos.Sinon_siContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.sinon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinon([NotNull] Cosmos.SinonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] Cosmos.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.expression_comparable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_comparable([NotNull] Cosmos.Expression_comparableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.expression_booleenne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_booleenne([NotNull] Cosmos.Expression_booleenneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.expression_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_numerique([NotNull] Cosmos.Expression_numeriqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.expression_textuelle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_textuelle([NotNull] Cosmos.Expression_textuelleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.atome_textuel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtome_textuel([NotNull] Cosmos.Atome_textuelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.atome_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtome_numerique([NotNull] Cosmos.Atome_numeriqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.chaine_de_caractere"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChaine_de_caractere([NotNull] Cosmos.Chaine_de_caractereContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="Cosmos.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNombre([NotNull] Cosmos.NombreContext context);
}
} // namespace lib.antlr
