//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/lib/../grammar/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lib.antlr {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="CosmosParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ICosmosVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.programme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgramme([NotNull] CosmosParser.ProgrammeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.entete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntete([NotNull] CosmosParser.EnteteContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.auteur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAuteur([NotNull] CosmosParser.AuteurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDate([NotNull] CosmosParser.DateContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.entreprise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEntreprise([NotNull] CosmosParser.EntrepriseContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDescription([NotNull] CosmosParser.DescriptionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.mainStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainStart([NotNull] CosmosParser.MainStartContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.mainEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainEnd([NotNull] CosmosParser.MainEndContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] CosmosParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.noop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNoop([NotNull] CosmosParser.NoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_simple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_simple([NotNull] CosmosParser.Instruction_simpleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.instruction_complexe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction_complexe([NotNull] CosmosParser.Instruction_complexeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.afficher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAfficher([NotNull] CosmosParser.AfficherContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.allouer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAllouer([NotNull] CosmosParser.AllouerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.affecter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAffecter([NotNull] CosmosParser.AffecterContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.recuperer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitRecuperer([NotNull] CosmosParser.RecupererContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.placer_curseur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPlacer_curseur([NotNull] CosmosParser.Placer_curseurContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.generer_aleatoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGenerer_aleatoire([NotNull] CosmosParser.Generer_aleatoireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.dormir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDormir([NotNull] CosmosParser.DormirContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.colorier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitColorier([NotNull] CosmosParser.ColorierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.la_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLa_zone_memoire([NotNull] CosmosParser.La_zone_memoireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.une_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUne_zone_memoire([NotNull] CosmosParser.Une_zone_memoireContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.boucle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoucle([NotNull] CosmosParser.BoucleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.boucle_avec_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoucle_avec_variable([NotNull] CosmosParser.Boucle_avec_variableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection([NotNull] CosmosParser.SelectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.base_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBase_si([NotNull] CosmosParser.Base_siContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.sinon_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinon_si([NotNull] CosmosParser.Sinon_siContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.sinon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSinon([NotNull] CosmosParser.SinonContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] CosmosParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_comparable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_comparable([NotNull] CosmosParser.Expression_comparableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_booleenne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_booleenne([NotNull] CosmosParser.Expression_booleenneContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_numerique([NotNull] CosmosParser.Expression_numeriqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.expression_textuelle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_textuelle([NotNull] CosmosParser.Expression_textuelleContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.atome_textuel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtome_textuel([NotNull] CosmosParser.Atome_textuelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.atome_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAtome_numerique([NotNull] CosmosParser.Atome_numeriqueContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] CosmosParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.chaine_de_caractere"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitChaine_de_caractere([NotNull] CosmosParser.Chaine_de_caractereContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="CosmosParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNombre([NotNull] CosmosParser.NombreContext context);
}
} // namespace lib.antlr
