//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/lib/../grammar/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lib.antlr {
#pragma warning disable 3021

using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICosmosListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public partial class CosmosBaseListener : ICosmosListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.programme"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgramme([NotNull] Cosmos.ProgrammeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.programme"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgramme([NotNull] Cosmos.ProgrammeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.entete"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntete([NotNull] Cosmos.EnteteContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.entete"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntete([NotNull] Cosmos.EnteteContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.auteur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAuteur([NotNull] Cosmos.AuteurContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.auteur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAuteur([NotNull] Cosmos.AuteurContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDate([NotNull] Cosmos.DateContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.date"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDate([NotNull] Cosmos.DateContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.entreprise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEntreprise([NotNull] Cosmos.EntrepriseContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.entreprise"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEntreprise([NotNull] Cosmos.EntrepriseContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDescription([NotNull] Cosmos.DescriptionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.description"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDescription([NotNull] Cosmos.DescriptionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.mainStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainStart([NotNull] Cosmos.MainStartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.mainStart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainStart([NotNull] Cosmos.MainStartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.mainEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainEnd([NotNull] Cosmos.MainEndContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.mainEnd"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainEnd([NotNull] Cosmos.MainEndContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] Cosmos.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] Cosmos.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.noop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNoop([NotNull] Cosmos.NoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.noop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNoop([NotNull] Cosmos.NoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.instruction_simple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction_simple([NotNull] Cosmos.Instruction_simpleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.instruction_simple"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction_simple([NotNull] Cosmos.Instruction_simpleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.instruction_complexe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction_complexe([NotNull] Cosmos.Instruction_complexeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.instruction_complexe"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction_complexe([NotNull] Cosmos.Instruction_complexeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.afficher"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAfficher([NotNull] Cosmos.AfficherContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.afficher"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAfficher([NotNull] Cosmos.AfficherContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.allouer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAllouer([NotNull] Cosmos.AllouerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.allouer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAllouer([NotNull] Cosmos.AllouerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.affecter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAffecter([NotNull] Cosmos.AffecterContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.affecter"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAffecter([NotNull] Cosmos.AffecterContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.recuperer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRecuperer([NotNull] Cosmos.RecupererContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.recuperer"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRecuperer([NotNull] Cosmos.RecupererContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.placer_curseur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPlacer_curseur([NotNull] Cosmos.Placer_curseurContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.placer_curseur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPlacer_curseur([NotNull] Cosmos.Placer_curseurContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.generer_aleatoire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGenerer_aleatoire([NotNull] Cosmos.Generer_aleatoireContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.generer_aleatoire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGenerer_aleatoire([NotNull] Cosmos.Generer_aleatoireContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.dormir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDormir([NotNull] Cosmos.DormirContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.dormir"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDormir([NotNull] Cosmos.DormirContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.colorier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterColorier([NotNull] Cosmos.ColorierContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.colorier"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitColorier([NotNull] Cosmos.ColorierContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.decouper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDecouper([NotNull] Cosmos.DecouperContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.decouper"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDecouper([NotNull] Cosmos.DecouperContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.afficher_curseur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAfficher_curseur([NotNull] Cosmos.Afficher_curseurContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.afficher_curseur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAfficher_curseur([NotNull] Cosmos.Afficher_curseurContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.masquer_curseur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMasquer_curseur([NotNull] Cosmos.Masquer_curseurContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.masquer_curseur"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMasquer_curseur([NotNull] Cosmos.Masquer_curseurContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] Cosmos.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] Cosmos.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.la_zone_memoire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLa_zone_memoire([NotNull] Cosmos.La_zone_memoireContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.la_zone_memoire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLa_zone_memoire([NotNull] Cosmos.La_zone_memoireContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.une_zone_memoire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUne_zone_memoire([NotNull] Cosmos.Une_zone_memoireContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.une_zone_memoire"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUne_zone_memoire([NotNull] Cosmos.Une_zone_memoireContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.boucle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoucle([NotNull] Cosmos.BoucleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.boucle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoucle([NotNull] Cosmos.BoucleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.boucle_avec_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoucle_avec_variable([NotNull] Cosmos.Boucle_avec_variableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.boucle_avec_variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoucle_avec_variable([NotNull] Cosmos.Boucle_avec_variableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSelection([NotNull] Cosmos.SelectionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.selection"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSelection([NotNull] Cosmos.SelectionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.base_si"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBase_si([NotNull] Cosmos.Base_siContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.base_si"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBase_si([NotNull] Cosmos.Base_siContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.sinon_si"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinon_si([NotNull] Cosmos.Sinon_siContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.sinon_si"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinon_si([NotNull] Cosmos.Sinon_siContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.sinon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSinon([NotNull] Cosmos.SinonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.sinon"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSinon([NotNull] Cosmos.SinonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] Cosmos.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] Cosmos.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.expression_comparable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_comparable([NotNull] Cosmos.Expression_comparableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.expression_comparable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_comparable([NotNull] Cosmos.Expression_comparableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.expression_booleenne"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_booleenne([NotNull] Cosmos.Expression_booleenneContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.expression_booleenne"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_booleenne([NotNull] Cosmos.Expression_booleenneContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.expression_numerique"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_numerique([NotNull] Cosmos.Expression_numeriqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.expression_numerique"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_numerique([NotNull] Cosmos.Expression_numeriqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.expression_textuelle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression_textuelle([NotNull] Cosmos.Expression_textuelleContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.expression_textuelle"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression_textuelle([NotNull] Cosmos.Expression_textuelleContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.atome_textuel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtome_textuel([NotNull] Cosmos.Atome_textuelContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.atome_textuel"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtome_textuel([NotNull] Cosmos.Atome_textuelContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.atome_numerique"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtome_numerique([NotNull] Cosmos.Atome_numeriqueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.atome_numerique"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtome_numerique([NotNull] Cosmos.Atome_numeriqueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.chaine_de_caractere"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterChaine_de_caractere([NotNull] Cosmos.Chaine_de_caractereContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.chaine_de_caractere"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitChaine_de_caractere([NotNull] Cosmos.Chaine_de_caractereContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="Cosmos.nombre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNombre([NotNull] Cosmos.NombreContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="Cosmos.nombre"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNombre([NotNull] Cosmos.NombreContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
} // namespace lib.antlr
