//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.6.6
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /Volumes/nFo/data/etml/codespace/csharp/cosmos/src/lib/../grammar/Cosmos.g4 by ANTLR 4.6.6

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace lib.antlr {
#pragma warning disable 3021
using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CosmosParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.6.6")]
[System.CLSCompliant(false)]
public interface ICosmosListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.programme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgramme([NotNull] CosmosParser.ProgrammeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.programme"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgramme([NotNull] CosmosParser.ProgrammeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.entete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntete([NotNull] CosmosParser.EnteteContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.entete"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntete([NotNull] CosmosParser.EnteteContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.auteur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAuteur([NotNull] CosmosParser.AuteurContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.auteur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAuteur([NotNull] CosmosParser.AuteurContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDate([NotNull] CosmosParser.DateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.date"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDate([NotNull] CosmosParser.DateContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.entreprise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEntreprise([NotNull] CosmosParser.EntrepriseContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.entreprise"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEntreprise([NotNull] CosmosParser.EntrepriseContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDescription([NotNull] CosmosParser.DescriptionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.description"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDescription([NotNull] CosmosParser.DescriptionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.mainStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainStart([NotNull] CosmosParser.MainStartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.mainStart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainStart([NotNull] CosmosParser.MainStartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.mainEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainEnd([NotNull] CosmosParser.MainEndContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.mainEnd"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainEnd([NotNull] CosmosParser.MainEndContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] CosmosParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] CosmosParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.noop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNoop([NotNull] CosmosParser.NoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.noop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNoop([NotNull] CosmosParser.NoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.instruction_simple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction_simple([NotNull] CosmosParser.Instruction_simpleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.instruction_simple"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction_simple([NotNull] CosmosParser.Instruction_simpleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.instruction_complexe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction_complexe([NotNull] CosmosParser.Instruction_complexeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.instruction_complexe"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction_complexe([NotNull] CosmosParser.Instruction_complexeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.afficher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAfficher([NotNull] CosmosParser.AfficherContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.afficher"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAfficher([NotNull] CosmosParser.AfficherContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.allouer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAllouer([NotNull] CosmosParser.AllouerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.allouer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAllouer([NotNull] CosmosParser.AllouerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.affecter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAffecter([NotNull] CosmosParser.AffecterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.affecter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAffecter([NotNull] CosmosParser.AffecterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.recuperer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRecuperer([NotNull] CosmosParser.RecupererContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.recuperer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRecuperer([NotNull] CosmosParser.RecupererContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.placer_curseur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPlacer_curseur([NotNull] CosmosParser.Placer_curseurContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.placer_curseur"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPlacer_curseur([NotNull] CosmosParser.Placer_curseurContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.generer_aleatoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGenerer_aleatoire([NotNull] CosmosParser.Generer_aleatoireContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.generer_aleatoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGenerer_aleatoire([NotNull] CosmosParser.Generer_aleatoireContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.dormir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDormir([NotNull] CosmosParser.DormirContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.dormir"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDormir([NotNull] CosmosParser.DormirContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.colorier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterColorier([NotNull] CosmosParser.ColorierContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.colorier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitColorier([NotNull] CosmosParser.ColorierContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.decouper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDecouper([NotNull] CosmosParser.DecouperContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.decouper"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDecouper([NotNull] CosmosParser.DecouperContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.la_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLa_zone_memoire([NotNull] CosmosParser.La_zone_memoireContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.la_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLa_zone_memoire([NotNull] CosmosParser.La_zone_memoireContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.une_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUne_zone_memoire([NotNull] CosmosParser.Une_zone_memoireContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.une_zone_memoire"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUne_zone_memoire([NotNull] CosmosParser.Une_zone_memoireContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.boucle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoucle([NotNull] CosmosParser.BoucleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.boucle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoucle([NotNull] CosmosParser.BoucleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.boucle_avec_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoucle_avec_variable([NotNull] CosmosParser.Boucle_avec_variableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.boucle_avec_variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoucle_avec_variable([NotNull] CosmosParser.Boucle_avec_variableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSelection([NotNull] CosmosParser.SelectionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSelection([NotNull] CosmosParser.SelectionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.base_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBase_si([NotNull] CosmosParser.Base_siContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.base_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBase_si([NotNull] CosmosParser.Base_siContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.sinon_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSinon_si([NotNull] CosmosParser.Sinon_siContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.sinon_si"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSinon_si([NotNull] CosmosParser.Sinon_siContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.sinon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSinon([NotNull] CosmosParser.SinonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.sinon"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSinon([NotNull] CosmosParser.SinonContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CosmosParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CosmosParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.expression_comparable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_comparable([NotNull] CosmosParser.Expression_comparableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.expression_comparable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_comparable([NotNull] CosmosParser.Expression_comparableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.expression_booleenne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_booleenne([NotNull] CosmosParser.Expression_booleenneContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.expression_booleenne"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_booleenne([NotNull] CosmosParser.Expression_booleenneContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.expression_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_numerique([NotNull] CosmosParser.Expression_numeriqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.expression_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_numerique([NotNull] CosmosParser.Expression_numeriqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.expression_textuelle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression_textuelle([NotNull] CosmosParser.Expression_textuelleContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.expression_textuelle"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression_textuelle([NotNull] CosmosParser.Expression_textuelleContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.atome_textuel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtome_textuel([NotNull] CosmosParser.Atome_textuelContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.atome_textuel"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtome_textuel([NotNull] CosmosParser.Atome_textuelContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.atome_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtome_numerique([NotNull] CosmosParser.Atome_numeriqueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.atome_numerique"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtome_numerique([NotNull] CosmosParser.Atome_numeriqueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] CosmosParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] CosmosParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.chaine_de_caractere"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterChaine_de_caractere([NotNull] CosmosParser.Chaine_de_caractereContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.chaine_de_caractere"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitChaine_de_caractere([NotNull] CosmosParser.Chaine_de_caractereContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CosmosParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNombre([NotNull] CosmosParser.NombreContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CosmosParser.nombre"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNombre([NotNull] CosmosParser.NombreContext context);
}
} // namespace lib.antlr
